// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package google

const (
	ModelGemini36Flash                 = "gemini-3.6-flash"
	ModelGemini35Flash                 = "gemini-3.5-flash"
	ModelGemini35FlashLite             = "gemini-3.5-flash-lite"
	ModelGemini31ProPreview            = "gemini-3.1-pro-preview"
	ModelGemini31ProPreviewCustomTools = "gemini-3.1-pro-preview-customtools"
	ModelGemini31FlashLite             = "gemini-3.1-flash-lite"
	ModelGemini31FlashLitePreview      = "gemini-3.1-flash-lite-preview"
	ModelGemini31FlashLivePreview      = "gemini-3.1-flash-live-preview"
	ModelGemini31FlashTTSPreview       = "gemini-3.1-flash-tts-preview"
	ModelGemini31FlashLiteImage        = "gemini-3.1-flash-lite-image"
	ModelGemini31FlashImage            = "gemini-3.1-flash-image"
	ModelGemini31FlashImagePrev        = "gemini-3.1-flash-image-preview"
	ModelGemini3ProImage               = "gemini-3-pro-image"
	ModelGemini3ProImagePreview        = "gemini-3-pro-image-preview"
	ModelGemini3FlashPreview           = "gemini-3-flash-preview"
	// Deprecated: Use ModelGemini3ProImage.
	ModelGemini31ProImage = ModelGemini3ProImage
	// Deprecated: Model was shut down March 9, 2026. Use ModelGemini31ProPreview instead.
	ModelGemini3ProPreview  = "gemini-3-pro-preview"
	ModelGemini25Pro        = "gemini-2.5-pro"
	ModelGemini25ProLong    = "gemini-2.5-pro-long"
	ModelGemini25Flash      = "gemini-2.5-flash"
	ModelGemini25FlashLite  = "gemini-2.5-flash-lite"
	ModelGemini25FlashImage = "gemini-2.5-flash-image"
	ModelGemini25FlashTTS   = "gemini-2.5-flash-preview-tts"
	ModelGemini25ProTTS     = "gemini-2.5-pro-preview-tts"
	// Deprecated: Model was shut down March 31, 2026.
	ModelGemini20Flash = "gemini-2.0-flash"
	// Deprecated: Deprecated model.
	ModelGemini15Pro = "gemini-1.5-pro"
	// Deprecated: Deprecated model.
	ModelGemini15Flash = "gemini-1.5-flash"
)

// DefaultModel is generated from the catalog's default model.
var DefaultModel = ModelGemini25Pro
