// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package google

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{
	// Rates billed today. Google lists a scheduled increase to $1.50/$7.50 ($0.15 cache read) on 2027-01-01; revisit then.
	ModelGemini38Flash: {
		Model:          ModelGemini38Flash,
		InputPrice:     0.75,
		OutputPrice:    3.75,
		CacheReadPrice: 0.075,
		Currency:       "USD",
		UpdatedAt:      "2026-09-02",
	},
	// Rates billed today. Google lists a scheduled increase to $1.50/$7.50 ($0.15 cache read) on 2027-01-01; revisit then.
	ModelGemini37Flash: {
		Model:          ModelGemini37Flash,
		InputPrice:     0.75,
		OutputPrice:    3.75,
		CacheReadPrice: 0.075,
		Currency:       "USD",
		UpdatedAt:      "2026-09-01",
	},
	// Rates billed today. Google lists a scheduled increase to $1.50/$7.50 ($0.15 cache read) on 2027-01-01; revisit then.
	ModelGemini36Flash: {
		Model:          ModelGemini36Flash,
		InputPrice:     0.75,
		OutputPrice:    3.75,
		CacheReadPrice: 0.075,
		Currency:       "USD",
		UpdatedAt:      "2026-09-01",
	},
	ModelGemini35Flash: {
		Model:                    ModelGemini35Flash,
		InputPrice:               1.50,
		OutputPrice:              9.00,
		CacheReadPrice:           0.15,
		NonGlobalPriceMultiplier: 1.10,
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	ModelGemini35FlashLite: {
		Model:                    ModelGemini35FlashLite,
		InputPrice:               0.30,
		OutputPrice:              2.50,
		CacheReadPrice:           0.03,
		NonGlobalPriceMultiplier: 1.10,
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	// Input $2.00 up to 200K tokens, $4.00 above; output $12.00 up to 200K tokens, $18.00 above.
	ModelGemini31ProPreview: {
		Model:                     ModelGemini31ProPreview,
		InputPrice:                2.00,
		OutputPrice:               12.00,
		LongContextInputPrice:     4.00,
		LongContextCacheReadPrice: 0.40,
		LongContextOutputPrice:    18.00,
		CacheReadPrice:            0.20,
		LongContextThreshold:      200001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-07-21",
	},
	// Up to 200K tokens ($4.00 over 200K) $18.00 over 200K tokens
	ModelGemini31ProPreviewCustomTools: {
		Model:                     ModelGemini31ProPreviewCustomTools,
		InputPrice:                2.00,
		OutputPrice:               12.00,
		LongContextInputPrice:     4.00,
		LongContextCacheReadPrice: 0.40,
		LongContextOutputPrice:    18.00,
		CacheReadPrice:            0.20,
		LongContextThreshold:      200001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-07-21",
	},
	// text/image/video ($0.50 audio)
	ModelGemini31FlashLite: {
		Model:                    ModelGemini31FlashLite,
		InputPrice:               0.25,
		OutputPrice:              1.50,
		CacheReadPrice:           0.025,
		NonGlobalPriceMultiplier: 1.10,
		InputPriceByModality:     map[string]float64{"audio": 0.50},
		CacheReadPriceByModality: map[string]float64{"audio": 0.05},
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	// Live API rates, shared by all three live models. Base is text; audio input is $3.00
	// and image/video $1.00, audio output $12.00. Google also quotes the audio rates per
	// minute ($0.005 in, $0.018 out), which the token tables cannot express.
	ModelGemini38Live: {
		Model:                 ModelGemini38Live,
		InputPrice:            0.75,
		OutputPrice:           4.50,
		InputPriceByModality:  map[string]float64{"audio": 3.00, "image": 1.00, "video": 1.00},
		OutputPriceByModality: map[string]float64{"audio": 12.00},
		Currency:              "USD",
		UpdatedAt:             "2026-09-17",
	},
	// Live API rates, shared by all three live models. Base is text; audio input is $3.00
	// and image/video $1.00, audio output $12.00. Google also quotes the audio rates per
	// minute ($0.005 in, $0.018 out), which the token tables cannot express.
	ModelGemini38LiveExtendedThinking: {
		Model:                 ModelGemini38LiveExtendedThinking,
		InputPrice:            0.75,
		OutputPrice:           4.50,
		InputPriceByModality:  map[string]float64{"audio": 3.00, "image": 1.00, "video": 1.00},
		OutputPriceByModality: map[string]float64{"audio": 12.00},
		Currency:              "USD",
		UpdatedAt:             "2026-09-17",
	},
	// Live API rates, shared by all three live models. Base is text; audio input is $3.00
	// and image/video $1.00, audio output $12.00. Google also quotes the audio rates per
	// minute ($0.005 in, $0.018 out), which the token tables cannot express.
	ModelGemini31FlashLivePreview: {
		Model:                 ModelGemini31FlashLivePreview,
		InputPrice:            0.75,
		OutputPrice:           4.50,
		InputPriceByModality:  map[string]float64{"audio": 3.00, "image": 1.00, "video": 1.00},
		OutputPriceByModality: map[string]float64{"audio": 12.00},
		Currency:              "USD",
		UpdatedAt:             "2026-09-17",
	},
	ModelGemini31FlashLitePreview: {
		Model:       ModelGemini31FlashLitePreview,
		InputPrice:  0.10,
		OutputPrice: 0.40,
		Currency:    "USD",
		UpdatedAt:   "2026-03-10",
	},
	ModelGemini31FlashImagePrev: {
		Model:       ModelGemini31FlashImagePrev,
		InputPrice:  0.50,
		OutputPrice: 3.00,
		Currency:    "USD",
		UpdatedAt:   "2026-03-10",
	},
	ModelGemini3FlashPreview: {
		Model:                    ModelGemini3FlashPreview,
		InputPrice:               0.50,
		OutputPrice:              3.00,
		CacheReadPrice:           0.05,
		InputPriceByModality:     map[string]float64{"audio": 1.00},
		CacheReadPriceByModality: map[string]float64{"audio": 0.10},
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	ModelGemini25Flash: {
		Model:                    ModelGemini25Flash,
		InputPrice:               0.30,
		OutputPrice:              2.50,
		CacheReadPrice:           0.03,
		InputPriceByModality:     map[string]float64{"audio": 1.00},
		CacheReadPriceByModality: map[string]float64{"audio": 0.10},
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	ModelGemini25FlashLite: {
		Model:                    ModelGemini25FlashLite,
		InputPrice:               0.10,
		OutputPrice:              0.40,
		CacheReadPrice:           0.01,
		InputPriceByModality:     map[string]float64{"audio": 0.30},
		CacheReadPriceByModality: map[string]float64{"audio": 0.03},
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	// Input $1.25 up to 200K tokens, $2.50 above; output $10.00 up to 200K tokens, $15.00 above.
	ModelGemini25Pro: {
		Model:                     ModelGemini25Pro,
		InputPrice:                1.25,
		OutputPrice:               10.00,
		LongContextInputPrice:     2.50,
		LongContextCacheReadPrice: 0.25,
		LongContextOutputPrice:    15.00,
		CacheReadPrice:            0.125,
		LongContextThreshold:      200001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-07-21",
	},
	ModelGemini20Flash: {
		Model:                    ModelGemini20Flash,
		InputPrice:               0.10,
		OutputPrice:              0.40,
		CacheReadPrice:           0.025,
		InputPriceByModality:     map[string]float64{"audio": 0.70},
		CacheReadPriceByModality: map[string]float64{"audio": 0.175},
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	ModelGemini15Pro: {
		Model:       ModelGemini15Pro,
		InputPrice:  1.25,
		OutputPrice: 5.00,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelGemini15Flash: {
		Model:       ModelGemini15Flash,
		InputPrice:  0.15,
		OutputPrice: 0.60,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
}

// ImageModelPricing is generated from catalog.json.
var ImageModelPricing = map[string]llm.ImagePricingInfo{
	// Text input and output match Gemini 2.5 Flash. Generated images bill as output
	// tokens at $30.00/1M; a 1024x1024 image is 1290 tokens, about $0.039. Deprecated,
	// shutting down 2026-10-02.
	ModelGemini25FlashImage: {
		Model: ModelGemini25FlashImage,
		TokenPricing: &llm.PricingInfo{
			Model:                 ModelGemini25FlashImage,
			InputPrice:            0.30,
			OutputPrice:           2.50,
			OutputPriceByModality: map[string]float64{"image": 30.00},
			Currency:              "USD",
			UpdatedAt:             "2026-09-17",
		},
		Currency:  "USD",
		UpdatedAt: "2026-09-17",
	},
	// Input covers text, image, and video. Generated images bill as output tokens
	// at $30.00/1M, about $0.0336 for a 1K-resolution image.
	ModelGemini31FlashLiteImage: {
		Model: ModelGemini31FlashLiteImage,
		TokenPricing: &llm.PricingInfo{
			Model:                 ModelGemini31FlashLiteImage,
			InputPrice:            0.25,
			OutputPrice:           1.50,
			OutputPriceByModality: map[string]float64{"image": 30.00},
			Currency:              "USD",
			UpdatedAt:             "2026-09-17",
		},
		Currency:  "USD",
		UpdatedAt: "2026-09-17",
	},
	// Generated images bill as output tokens at $60.00/1M: about $0.045 at 0.5K,
	// $0.067 at 1K, $0.101 at 2K, and $0.151 at 4K.
	ModelGemini31FlashImage: {
		Model: ModelGemini31FlashImage,
		TokenPricing: &llm.PricingInfo{
			Model:                 ModelGemini31FlashImage,
			InputPrice:            0.50,
			OutputPrice:           3.00,
			OutputPriceByModality: map[string]float64{"image": 60.00},
			Currency:              "USD",
			UpdatedAt:             "2026-09-17",
		},
		Currency:  "USD",
		UpdatedAt: "2026-09-17",
	},
	// Text input and output match Gemini 3.1 Pro; generated images bill as output
	// tokens at $120.00/1M -- about $0.134 for a 1K or 2K image and $0.24 at 4K. The
	// rate is recorded rather than a per-image constant, which is only right at one size.
	ModelGemini3ProImage: {
		Model: ModelGemini3ProImage,
		TokenPricing: &llm.PricingInfo{
			Model:                 ModelGemini3ProImage,
			InputPrice:            2.00,
			OutputPrice:           12.00,
			OutputPriceByModality: map[string]float64{"image": 120.00},
			Currency:              "USD",
			UpdatedAt:             "2026-09-17",
		},
		Currency:  "USD",
		UpdatedAt: "2026-09-17",
	},
}

// EmbeddingModelPricing is generated from catalog.json.
var EmbeddingModelPricing = map[string]llm.EmbeddingPricingInfo{
	// Text-only embeddings; free of charge on the free tier
	"gemini-embedding-001": {
		Model:     "gemini-embedding-001",
		Price:     0.15,
		Currency:  "USD",
		UpdatedAt: "2026-08-09",
	},
	// Multimodal embeddings; text input price. Image, audio, and video inputs are billed at separate rates
	"gemini-embedding-2": {
		Model:     "gemini-embedding-2",
		Price:     0.20,
		Currency:  "USD",
		UpdatedAt: "2026-08-09",
	},
}
