// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package google

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{
	// Rates billed today. Google lists a scheduled increase to $1.50/$7.50 ($0.15 cache read) on 2027-01-01; revisit then.
	ModelGemini38Flash: {
		Model:          ModelGemini38Flash,
		InputPrice:     0.75,
		OutputPrice:    3.75,
		CacheReadPrice: 0.075,
		Currency:       "USD",
		UpdatedAt:      "2026-09-02",
	},
	// Rates billed today. Google lists a scheduled increase to $1.50/$7.50 ($0.15 cache read) on 2027-01-01; revisit then.
	ModelGemini37Flash: {
		Model:          ModelGemini37Flash,
		InputPrice:     0.75,
		OutputPrice:    3.75,
		CacheReadPrice: 0.075,
		Currency:       "USD",
		UpdatedAt:      "2026-09-01",
	},
	// Rates billed today. Google lists a scheduled increase to $1.50/$7.50 ($0.15 cache read) on 2027-01-01; revisit then.
	ModelGemini36Flash: {
		Model:          ModelGemini36Flash,
		InputPrice:     0.75,
		OutputPrice:    3.75,
		CacheReadPrice: 0.075,
		Currency:       "USD",
		UpdatedAt:      "2026-09-01",
	},
	ModelGemini35Flash: {
		Model:                    ModelGemini35Flash,
		InputPrice:               1.50,
		OutputPrice:              9.00,
		CacheReadPrice:           0.15,
		NonGlobalPriceMultiplier: 1.10,
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	ModelGemini35FlashLite: {
		Model:                    ModelGemini35FlashLite,
		InputPrice:               0.30,
		OutputPrice:              2.50,
		CacheReadPrice:           0.03,
		NonGlobalPriceMultiplier: 1.10,
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	// Input $2.00 up to 200K tokens, $4.00 above; output $12.00 up to 200K tokens, $18.00 above.
	ModelGemini31ProPreview: {
		Model:                     ModelGemini31ProPreview,
		InputPrice:                2.00,
		OutputPrice:               12.00,
		LongContextInputPrice:     4.00,
		LongContextCacheReadPrice: 0.40,
		LongContextOutputPrice:    18.00,
		CacheReadPrice:            0.20,
		LongContextThreshold:      200001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-07-21",
	},
	// Up to 200K tokens ($4.00 over 200K) $18.00 over 200K tokens
	ModelGemini31ProPreviewCustomTools: {
		Model:                     ModelGemini31ProPreviewCustomTools,
		InputPrice:                2.00,
		OutputPrice:               12.00,
		LongContextInputPrice:     4.00,
		LongContextCacheReadPrice: 0.40,
		LongContextOutputPrice:    18.00,
		CacheReadPrice:            0.20,
		LongContextThreshold:      200001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-07-21",
	},
	// text/image/video ($0.50 audio)
	ModelGemini31FlashLite: {
		Model:                    ModelGemini31FlashLite,
		InputPrice:               0.25,
		OutputPrice:              1.50,
		CacheReadPrice:           0.025,
		NonGlobalPriceMultiplier: 1.10,
		InputPriceByModality:     map[string]float64{"audio": 0.50},
		CacheReadPriceByModality: map[string]float64{"audio": 0.05},
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	// text input text output
	ModelGemini31FlashLivePreview: {
		Model:       ModelGemini31FlashLivePreview,
		InputPrice:  0.75,
		OutputPrice: 4.50,
		Currency:    "USD",
		UpdatedAt:   "2026-05-28",
	},
	ModelGemini31FlashLitePreview: {
		Model:       ModelGemini31FlashLitePreview,
		InputPrice:  0.10,
		OutputPrice: 0.40,
		Currency:    "USD",
		UpdatedAt:   "2026-03-10",
	},
	ModelGemini31FlashImagePrev: {
		Model:       ModelGemini31FlashImagePrev,
		InputPrice:  0.50,
		OutputPrice: 3.00,
		Currency:    "USD",
		UpdatedAt:   "2026-03-10",
	},
	ModelGemini3FlashPreview: {
		Model:                    ModelGemini3FlashPreview,
		InputPrice:               0.50,
		OutputPrice:              3.00,
		CacheReadPrice:           0.05,
		InputPriceByModality:     map[string]float64{"audio": 1.00},
		CacheReadPriceByModality: map[string]float64{"audio": 0.10},
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	ModelGemini25Flash: {
		Model:                    ModelGemini25Flash,
		InputPrice:               0.30,
		OutputPrice:              2.50,
		CacheReadPrice:           0.03,
		InputPriceByModality:     map[string]float64{"audio": 1.00},
		CacheReadPriceByModality: map[string]float64{"audio": 0.10},
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	ModelGemini25FlashLite: {
		Model:                    ModelGemini25FlashLite,
		InputPrice:               0.10,
		OutputPrice:              0.40,
		CacheReadPrice:           0.01,
		InputPriceByModality:     map[string]float64{"audio": 0.30},
		CacheReadPriceByModality: map[string]float64{"audio": 0.03},
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	// Input $1.25 up to 200K tokens, $2.50 above; output $10.00 up to 200K tokens, $15.00 above.
	ModelGemini25Pro: {
		Model:                     ModelGemini25Pro,
		InputPrice:                1.25,
		OutputPrice:               10.00,
		LongContextInputPrice:     2.50,
		LongContextCacheReadPrice: 0.25,
		LongContextOutputPrice:    15.00,
		CacheReadPrice:            0.125,
		LongContextThreshold:      200001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-07-21",
	},
	ModelGemini20Flash: {
		Model:                    ModelGemini20Flash,
		InputPrice:               0.10,
		OutputPrice:              0.40,
		CacheReadPrice:           0.025,
		InputPriceByModality:     map[string]float64{"audio": 0.70},
		CacheReadPriceByModality: map[string]float64{"audio": 0.175},
		Currency:                 "USD",
		UpdatedAt:                "2026-07-21",
	},
	ModelGemini15Pro: {
		Model:       ModelGemini15Pro,
		InputPrice:  1.25,
		OutputPrice: 5.00,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelGemini15Flash: {
		Model:       ModelGemini15Flash,
		InputPrice:  0.15,
		OutputPrice: 0.60,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
}

// ImageModelPricing is generated from catalog.json.
var ImageModelPricing = map[string]llm.ImagePricingInfo{
	// $30 per 1M tokens, 1290 tokens per 1024x1024 image
	ModelGemini25FlashImage: {
		Model:     ModelGemini25FlashImage,
		Price:     0.039,
		MaxSize:   "1024x1024",
		Currency:  "USD",
		UpdatedAt: "2026-06-30",
	},
	// $30 per 1M output tokens; 1120 tokens per 1K image
	ModelGemini31FlashLiteImage: {
		Model:     ModelGemini31FlashLiteImage,
		Price:     0.0336,
		MaxSize:   "1024x1024",
		Currency:  "USD",
		UpdatedAt: "2026-06-30",
	},
	// $60 per 1M output tokens; ~$0.067 per 1K-resolution image
	ModelGemini31FlashImage: {
		Model:     ModelGemini31FlashImage,
		Price:     0.067,
		MaxSize:   "4096x4096",
		Currency:  "USD",
		UpdatedAt: "2026-06-30",
	},
	// $120 per 1M output tokens; ~$0.134 per 1K/2K image ($0.24 at 4K)
	ModelGemini3ProImage: {
		Model:     ModelGemini3ProImage,
		Price:     0.134,
		MaxSize:   "4096x4096",
		Currency:  "USD",
		UpdatedAt: "2026-06-30",
	},
}

// EmbeddingModelPricing is generated from catalog.json.
var EmbeddingModelPricing = map[string]llm.EmbeddingPricingInfo{
	// Text-only embeddings; free of charge on the free tier
	"gemini-embedding-001": {
		Model:     "gemini-embedding-001",
		Price:     0.15,
		Currency:  "USD",
		UpdatedAt: "2026-08-09",
	},
	// Multimodal embeddings; text input price. Image, audio, and video inputs are billed at separate rates
	"gemini-embedding-2": {
		Model:     "gemini-embedding-2",
		Price:     0.20,
		Currency:  "USD",
		UpdatedAt: "2026-08-09",
	},
}
