package google

import (
	"encoding/base64"
	"encoding/json"
	"testing"

	"github.com/deepnoodle-ai/dive/llm"
	"github.com/deepnoodle-ai/wonton/assert"
	"google.golang.org/genai"
)

func TestGenerateToolCallIDUnique(t *testing.T) {
	// The same tool called repeatedly must get distinct IDs, since tool
	// result matching is keyed by ID.
	seen := map[string]bool{}
	for i := 0; i < 10; i++ {
		id := generateToolCallID("calculator")
		assert.False(t, seen[id])
		seen[id] = true
	}
}

func TestMessagesToContentsToolRoundTrip(t *testing.T) {
	// A tool use ID generated by the provider is carried on the message
	// content, so converting back to Google format matches results to calls
	// by the stored ID.
	id := generateToolCallID("calculator")
	messages := []*llm.Message{
		llm.NewUserTextMessage("What is 1+1?"),
		{
			Role: llm.Assistant,
			Content: []llm.Content{
				&llm.ToolUseContent{
					ID:    id,
					Name:  "calculator",
					Input: []byte(`{"expression":"1+1"}`),
					ProviderMetadata: map[string]string{
						googleThoughtSignatureMetadataKey: base64.StdEncoding.EncodeToString([]byte("sig-123")),
					},
				},
			},
		},
		llm.NewToolResultMessage(&llm.ToolResultContent{
			ToolUseID: id,
			Content:   "2",
		}),
	}
	contents, err := messagesToContents(messages)
	assert.NoError(t, err)
	assert.Len(t, contents, 3)
	assert.NotNil(t, contents[1].Parts[0].FunctionCall)
	assert.Equal(t, contents[1].Parts[0].FunctionCall.ID, id)
	assert.Equal(t, []byte("sig-123"), contents[1].Parts[0].ThoughtSignature)
	assert.NotNil(t, contents[2].Parts[0].FunctionResponse)
	assert.Equal(t, contents[2].Parts[0].FunctionResponse.ID, id)
	assert.Equal(t, contents[2].Parts[0].FunctionResponse.Name, "calculator")
}

func TestGoogleThoughtSignatureSurvivesMessageRoundTrip(t *testing.T) {
	signature := []byte("opaque-google-signature")
	resp := &genai.GenerateContentResponse{
		Candidates: []*genai.Candidate{
			{
				Index: 0,
				Content: &genai.Content{
					Role: "model",
					Parts: []*genai.Part{
						{
							FunctionCall: &genai.FunctionCall{
								ID:   "call_1",
								Name: "default_api:mobius",
								Args: map[string]any{"command": "status"},
							},
							ThoughtSignature: signature,
						},
					},
				},
			},
		},
	}

	converted, err := convertGoogleResponse(resp, "gemini-3.1-flash-lite")
	assert.NoError(t, err)
	assert.Len(t, converted.Content, 1)

	toolUse, ok := converted.Content[0].(*llm.ToolUseContent)
	assert.True(t, ok)
	assert.Equal(t, base64.StdEncoding.EncodeToString(signature), toolUse.ProviderMetadata[googleThoughtSignatureMetadataKey])

	body, err := json.Marshal(converted.Message())
	assert.NoError(t, err)
	var replayed llm.Message
	assert.NoError(t, json.Unmarshal(body, &replayed))

	contents, err := messagesToContents([]*llm.Message{
		&replayed,
		llm.NewToolResultMessage(&llm.ToolResultContent{
			ToolUseID: toolUse.ID,
			Content:   "ok",
		}),
	})
	assert.NoError(t, err)
	assert.Len(t, contents, 2)
	assert.Equal(t, signature, contents[0].Parts[0].ThoughtSignature)
}
