package main

import (
	"context"
	"flag"
	"fmt"
	"log"

	"github.com/deepnoodle-ai/dive/media"
	diveopenai "github.com/deepnoodle-ai/dive/providers/openai"
)

func main() {
	var (
		text               string
		out                string
		voice              string
		format             string
		ttsModel           string
		transcriptionModel string
		transcribe         bool
	)
	flag.StringVar(&text, "text", "Welcome to Dive text-to-speech.", "text to synthesize")
	flag.StringVar(&out, "out", "openai-text-to-speech", "output path; extension is added if omitted")
	flag.StringVar(&voice, "voice", "alloy", "OpenAI voice name")
	flag.StringVar(&format, "format", "mp3", "audio format: mp3, opus, aac, flac, wav, or pcm")
	flag.StringVar(&ttsModel, "tts-model", diveopenai.ModelGPT4oMiniTTS, "OpenAI text-to-speech model")
	flag.StringVar(&transcriptionModel, "transcription-model", diveopenai.ModelGPT4oMiniTranscribe, "OpenAI transcription model")
	flag.BoolVar(&transcribe, "transcribe", true, "transcribe the generated audio")
	flag.Parse()

	audioFormat := media.AudioFormat(format)
	if err := media.ValidateAudioFormat(audioFormat); err != nil {
		log.Fatal(err)
	}

	ctx := context.Background()
	audio, err := media.TextToSpeech(ctx, text,
		media.WithModel(ttsModel),
		media.WithVoice(voice),
		media.WithAudioFormat(audioFormat),
		media.WithVoiceInstructions("Speak clearly and naturally."),
	)
	if err != nil {
		log.Fatal(err)
	}

	path, err := audio.WriteTo(out)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Saved %s (%s, %s, %d bytes)\n", path, audio.Model, audio.Format, len(audio.Data))

	if !transcribe {
		return
	}

	transcript, err := media.Transcribe(ctx, audio.Data,
		media.WithModel(transcriptionModel),
		media.WithAudioMIMEType(audio.MimeType),
		media.WithTranscriptionPrompt("The audio was generated by a Dive example."),
	)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("\nTranscript:\n%s\n", transcript.Text)
}
