// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package deepinfra

const (
	ModelGLM53Flash      = "zai-org/GLM-5.3-Flash"
	ModelGLM53           = "zai-org/GLM-5.3"
	ModelQwen38Flash     = "Qwen/Qwen3.8-Flash"
	ModelQwen38Max       = "Qwen/Qwen3.8-Max"
	ModelQwen38A95B      = "Qwen/Qwen3.8-2.4T-A95B"
	ModelQwen3827B       = "Qwen/Qwen3.8-27B"
	ModelKimiK3          = "moonshotai/Kimi-K3"
	ModelDeepSeekV4Flash = "deepseek-ai/DeepSeek-V4-Flash-0731"
)

// DefaultModel is generated from the catalog's default model.
var DefaultModel = ModelGLM53Flash
