// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package deepinfra

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{}
