// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package anthropic

const (
	FeatureOutput128k    = "output-128k-2025-02-19"
	FeatureExtendedCache = "extended-cache-ttl-2025-04-11"
	FeaturePromptCaching = "prompt-caching-2024-07-31"
	// Deprecated: Use FeatureMCPClientV2 instead.
	FeatureMCPClient           = "mcp-client-2025-04-04"
	FeatureContextManagement   = "context-management-2025-06-27"
	FeatureCodeExecution       = "code-execution-2025-08-25"
	FeatureCodeExecutionLegacy = "code-execution-2025-05-22"
	FeatureComputerUse         = "computer-use-2025-01-24"
	FeatureComputerUse45_46    = "computer-use-2025-11-24"
	// Deprecated: Use FeatureComputerUse45_46 instead.
	FeatureComputerUseOpus45   = FeatureComputerUse45_46
	FeatureContext1M           = "context-1m-2025-08-07"
	FeatureFastMode            = "fast-mode-2026-02-01"
	FeatureOutput300k          = "output-300k-2026-03-24"
	FeatureCompact             = "compact-2026-01-12"
	FeatureMCPClientV2         = "mcp-client-2025-11-20"
	FeatureFilesAPI            = "files-api-2025-04-14"
	FeatureInterleavedThinking = "interleaved-thinking-2025-05-14"
)
