// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package anthropic

const (
	ModelClaude35Haiku20241022  = "claude-3-5-haiku-20241022"
	ModelClaude35Sonnet20241022 = "claude-3-5-sonnet-20241022"
	ModelClaude37Sonnet20250219 = "claude-3-7-sonnet-20250219"
	ModelClaudeSonnet420250514  = "claude-sonnet-4-20250514"
	ModelClaudeOpus420250514    = "claude-opus-4-20250514"
	ModelClaudeOpus4120250805   = "claude-opus-4-1-20250805"
	ModelClaudeHaiku4520251001  = "claude-haiku-4-5-20251001"
	ModelClaudeSonnet4520250929 = "claude-sonnet-4-5-20250929"
	ModelClaudeOpus4520251101   = "claude-opus-4-5-20251101"
	ModelClaudeHaiku45          = "claude-haiku-4-5"
	ModelClaudeSonnet45         = "claude-sonnet-4-5"
	ModelClaudeOpus45           = "claude-opus-4-5"
	ModelClaudeSonnet46         = "claude-sonnet-4-6"
	ModelClaudeOpus46           = "claude-opus-4-6"
	ModelClaudeOpus47           = "claude-opus-4-7"
	ModelClaudeOpus48           = "claude-opus-4-8"
	ModelClaudeOpus5            = "claude-opus-5"
	ModelClaudeFable5           = "claude-fable-5"
	ModelClaudeMythos5          = "claude-mythos-5"
	ModelClaudeSonnet5          = "claude-sonnet-5"
)

// DefaultModel is generated from the catalog's default model.
var DefaultModel = ModelClaudeSonnet5
