package main

import (
	"context"
	"flag"
	"fmt"
	"log"

	"github.com/deepnoodle-ai/dive/media"
	diveopenai "github.com/deepnoodle-ai/dive/providers/openai"
)

func main() {
	var (
		text               string
		out                string
		voice              string
		format             string
		speechModel        string
		transcriptionModel string
		transcribe         bool
	)
	flag.StringVar(&text, "text", "Welcome to Dive speech generation.", "text to synthesize")
	flag.StringVar(&out, "out", "openai-speech", "output path; extension is added if omitted")
	flag.StringVar(&voice, "voice", "alloy", "OpenAI voice name")
	flag.StringVar(&format, "format", "mp3", "audio format: mp3, opus, aac, flac, wav, or pcm")
	flag.StringVar(&speechModel, "speech-model", diveopenai.ModelGPT4oMiniTTS, "OpenAI speech model")
	flag.StringVar(&transcriptionModel, "transcription-model", diveopenai.ModelGPT4oMiniTranscribe, "OpenAI transcription model")
	flag.BoolVar(&transcribe, "transcribe", true, "transcribe the generated audio")
	flag.Parse()

	audioFormat := media.AudioFormat(format)
	if err := media.ValidateAudioFormat(audioFormat); err != nil {
		log.Fatal(err)
	}

	ctx := context.Background()
	speech, err := media.GenerateSpeech(ctx, text,
		media.WithModel(speechModel),
		media.WithVoice(voice),
		media.WithAudioFormat(audioFormat),
		media.WithSpeechInstructions("Speak clearly and naturally."),
	)
	if err != nil {
		log.Fatal(err)
	}

	path, err := speech.WriteTo(out)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("Saved %s (%s, %s, %d bytes)\n", path, speech.Model, speech.Format, len(speech.Data))

	if !transcribe {
		return
	}

	transcript, err := media.TranscribeSpeech(ctx, speech.Data,
		media.WithModel(transcriptionModel),
		media.WithAudioMIMEType(speech.MimeType),
		media.WithTranscriptionPrompt("The audio was generated by a Dive example."),
	)
	if err != nil {
		log.Fatal(err)
	}
	fmt.Printf("\nTranscript:\n%s\n", transcript.Text)
}
