Name: 'Deterministic File Inputs Example'
Description: 'Demonstrates how filesystem inputs are tracked for deterministic execution'

Inputs:
  - Name: 'topic'
    Description: 'Topic to analyze in the files'
    Default: 'documentation quality'

Steps:
  - Name: 'Analyze Files'
    Type: prompt
    Prompt: 'Analyze these files and provide insights about ${inputs.topic}. Focus on patterns, quality, and recommendations.'
    Content:
      # All markdown files in the current directory will be tracked by content hash
      - Path: '*.md'
      # Individual files are also tracked
      - Path: 'workflow.yaml'
    Agent: 'gpt-4o-mini'
    Store: 'analysis_result'

  - Name: 'Generate Summary'
    Type: prompt
    Prompt: 'Based on the analysis: ${state.analysis_result}, create a concise summary of findings and top 3 recommendations.'
    Agent: 'gpt-4o-mini'
