// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package openai

import (
	"bytes"
	_ "embed"

	"github.com/deepnoodle-ai/dive/providers/modelcatalog"
)

//go:embed catalog.json
var embeddedCatalogJSON []byte

var embeddedCatalog = modelcatalog.MustParse("openai", embeddedCatalogJSON)

// Catalog returns a copy of this provider's embedded model catalog.
func Catalog() modelcatalog.Catalog {
	return embeddedCatalog.Clone()
}

// CatalogJSON returns a copy of the canonical embedded catalog document.
func CatalogJSON() []byte {
	return bytes.Clone(embeddedCatalogJSON)
}
