// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package openai

import (
	openaisdk "github.com/openai/openai-go/v3"
)

const (
	ModelGPT6Astra       openaisdk.ChatModel = "gpt-6-astra"
	ModelGPT56                               = "gpt-5.6"
	ModelGPT56Sol        openaisdk.ChatModel = "gpt-5.6-sol"
	ModelGPT56Terra      openaisdk.ChatModel = "gpt-5.6-terra"
	ModelGPT56Luna       openaisdk.ChatModel = "gpt-5.6-luna"
	ModelGPT55                               = "gpt-5.5"
	ModelGPT54                               = "gpt-5.4"
	ModelGPT54Mini                           = "gpt-5.4-mini"
	ModelGPT54Nano                           = "gpt-5.4-nano"
	ModelGPT53ChatLatest                     = "gpt-5.3-chat-latest"
	// Deprecated: Use ModelGPT53ChatLatest.
	ModelGPT53ChatLast               = ModelGPT53ChatLatest
	ModelGPT52                       = "gpt-5.2"
	ModelGPT52Pro                    = "gpt-5.2-pro"
	ModelGPT51                       = "gpt-5.1"
	ModelGPT5                        = "gpt-5"
	ModelGPT5Pro                     = "gpt-5-pro"
	ModelGPT5Mini                    = "gpt-5-mini"
	ModelGPT5Nano                    = "gpt-5-nano"
	ModelGPT41                       = "gpt-4.1"
	ModelGPT4o                       = "gpt-4o"
	ModelGPTImage2                   = "gpt-image-2"
	ModelGPTImage220260421           = "gpt-image-2-2026-04-21"
	ModelGPTImage15                  = "gpt-image-1.5"
	ModelGPTImage1                   = "gpt-image-1"
	ModelGPTImage1Mini               = "gpt-image-1-mini"
	ModelGPT4oMiniTTS                = "gpt-4o-mini-tts"
	ModelGPT4oMiniTTS20251215        = "gpt-4o-mini-tts-2025-12-15"
	ModelGPT4oTranscribe             = "gpt-4o-transcribe"
	ModelGPT4oMiniTranscribe         = "gpt-4o-mini-transcribe"
	ModelGPT4oMiniTranscribe20251215 = "gpt-4o-mini-transcribe-2025-12-15"
	ModelGPT4oTranscribeDiarize      = "gpt-4o-transcribe-diarize"
	ModelWhisper1                    = "whisper-1"
	ModelO3                          = "o3"
	ModelO3Pro                       = "o3-pro"
	ModelO3Mini                      = "o3-mini"
	ModelO4Mini                      = "o4-mini"
	ModelO3DeepResearch              = "o3-deep-research"
	ModelO4MiniDeepResearch          = "o4-mini-deep-research"
	ModelGPT53Codex                  = "gpt-5.3-codex"
	ModelGPT52Codex                  = "gpt-5.2-codex"
	ModelGPT51CodexMax               = "gpt-5.1-codex-max"
	ModelGPT51Codex                  = "gpt-5.1-codex"
	ModelGPT5Codex                   = "gpt-5-codex"
	ModelGPT5CodexMini               = "gpt-5-codex-mini"
	ModelCodexMiniLatest             = "codex-mini-latest"
	// Deprecated: Use ModelGPT53Codex instead.
	ModelCodex = ModelCodexMiniLatest
	// Deprecated: Use ModelCodexMiniLatest instead.
	ModelCodexAsk = "codex-ask"
)

// DefaultModel is generated from the catalog's default model.
var DefaultModel = ModelGPT56Sol
