// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package openai

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{
	// Standard tier. Above 272K input tokens, input, cache read, and
	// cache write rates double and output is 1.5x.
	ModelGPT6Astra: {
		Model:                      ModelGPT6Astra,
		InputPrice:                 10.00,
		OutputPrice:                50.00,
		LongContextInputPrice:      20.00,
		LongContextCacheReadPrice:  2.00,
		LongContextOutputPrice:     75.00,
		CacheReadPrice:             1.00,
		CacheWritePrice:            12.50,
		LongContextCacheWritePrice: 25.00,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-05",
	},
	// Standard tier. Above 272K input tokens, input, cache read, and
	// cache write rates double and output is 1.5x.
	ModelGPT56: {
		Model:                      ModelGPT56,
		InputPrice:                 4.00,
		OutputPrice:                20.00,
		LongContextInputPrice:      8.00,
		LongContextCacheReadPrice:  0.80,
		LongContextOutputPrice:     30.00,
		CacheReadPrice:             0.40,
		CacheWritePrice:            5.00,
		LongContextCacheWritePrice: 10.00,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-09",
	},
	// Standard tier. Above 272K input tokens, input, cache read, and
	// cache write rates double and output is 1.5x.
	ModelGPT56Sol: {
		Model:                      ModelGPT56Sol,
		InputPrice:                 4.00,
		OutputPrice:                20.00,
		LongContextInputPrice:      8.00,
		LongContextCacheReadPrice:  0.80,
		LongContextOutputPrice:     30.00,
		CacheReadPrice:             0.40,
		CacheWritePrice:            5.00,
		LongContextCacheWritePrice: 10.00,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-09",
	},
	// Standard tier. Above 272K input tokens, input, cache read, and
	// cache write rates double and output is 1.5x.
	ModelGPT56Terra: {
		Model:                      ModelGPT56Terra,
		InputPrice:                 2.00,
		OutputPrice:                12.00,
		LongContextInputPrice:      4.00,
		LongContextCacheReadPrice:  0.40,
		LongContextOutputPrice:     18.00,
		CacheReadPrice:             0.20,
		CacheWritePrice:            2.50,
		LongContextCacheWritePrice: 5.00,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-09",
	},
	// Standard tier. Above 272K input tokens, input, cache read, and
	// cache write rates double and output is 1.5x.
	ModelGPT56Luna: {
		Model:                      ModelGPT56Luna,
		InputPrice:                 0.20,
		OutputPrice:                1.20,
		LongContextInputPrice:      0.40,
		LongContextCacheReadPrice:  0.04,
		LongContextOutputPrice:     1.80,
		CacheReadPrice:             0.02,
		CacheWritePrice:            0.25,
		LongContextCacheWritePrice: 0.50,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-09",
	},
	// Requires Daybreak program approval. gpt-daybreak-red-latest
	// aliases this model and is priced to match.
	ModelGPT56Cyber: {
		Model:           ModelGPT56Cyber,
		InputPrice:      12.50,
		OutputPrice:     75.00,
		CacheReadPrice:  1.25,
		CacheWritePrice: 15.625,
		Currency:        "USD",
		UpdatedAt:       "2026-09-09",
	},
	// Alias currently pointing at gpt-5.6-sol; OpenAI reprices the
	// alias to match whichever model it points at.
	ModelDaybreakBlueLatest: {
		Model:                      ModelDaybreakBlueLatest,
		InputPrice:                 4.00,
		OutputPrice:                20.00,
		LongContextInputPrice:      8.00,
		LongContextCacheReadPrice:  0.80,
		LongContextOutputPrice:     30.00,
		CacheReadPrice:             0.40,
		CacheWritePrice:            5.00,
		LongContextCacheWritePrice: 10.00,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-09",
	},
	// Alias currently pointing at gpt-5.6-cyber; OpenAI reprices the
	// alias to match whichever model it points at.
	ModelDaybreakRedLatest: {
		Model:           ModelDaybreakRedLatest,
		InputPrice:      12.50,
		OutputPrice:     75.00,
		CacheReadPrice:  1.25,
		CacheWritePrice: 15.625,
		Currency:        "USD",
		UpdatedAt:       "2026-09-09",
	},
	// Standard tier. Above 272K input tokens, input and cache read
	// double and output is 1.5x.
	ModelGPT55: {
		Model:                     ModelGPT55,
		InputPrice:                5.00,
		OutputPrice:               30.00,
		LongContextInputPrice:     10.00,
		LongContextCacheReadPrice: 1.00,
		LongContextOutputPrice:    45.00,
		CacheReadPrice:            0.50,
		LongContextThreshold:      272001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-09-09",
	},
	// Standard tier. Above 272K input tokens, input doubles and
	// output is 1.5x. OpenAI publishes no cached-input rate for the
	// pro models, so cache reads are zero in both tiers.
	ModelGPT55Pro: {
		Model:                     ModelGPT55Pro,
		InputPrice:                30.00,
		OutputPrice:               180.00,
		LongContextInputPrice:     60.00,
		LongContextCacheReadPrice: 0.00,
		LongContextOutputPrice:    270.00,
		LongContextThreshold:      272001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-09-09",
	},
	// Standard tier. Above 272K input tokens, input and cache read
	// double and output is 1.5x.
	ModelGPT54: {
		Model:                     ModelGPT54,
		InputPrice:                2.50,
		OutputPrice:               15.00,
		LongContextInputPrice:     5.00,
		LongContextCacheReadPrice: 0.50,
		LongContextOutputPrice:    22.50,
		CacheReadPrice:            0.25,
		LongContextThreshold:      272001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-09-09",
	},
	ModelGPT54Mini: {
		Model:          ModelGPT54Mini,
		InputPrice:     0.75,
		OutputPrice:    4.50,
		CacheReadPrice: 0.075,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT54Nano: {
		Model:          ModelGPT54Nano,
		InputPrice:     0.20,
		OutputPrice:    1.25,
		CacheReadPrice: 0.02,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	// Standard tier. Above 272K input tokens, input doubles and
	// output is 1.5x. OpenAI publishes no cached-input rate for the
	// pro models, so cache reads are zero in both tiers.
	ModelGPT54Pro: {
		Model:                     ModelGPT54Pro,
		InputPrice:                30.00,
		OutputPrice:               180.00,
		LongContextInputPrice:     60.00,
		LongContextCacheReadPrice: 0.00,
		LongContextOutputPrice:    270.00,
		LongContextThreshold:      272001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-09-09",
	},
	ModelGPT52: {
		Model:          ModelGPT52,
		InputPrice:     1.75,
		OutputPrice:    14.00,
		CacheReadPrice: 0.175,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT52Pro: {
		Model:       ModelGPT52Pro,
		InputPrice:  21.00,
		OutputPrice: 168.00,
		Currency:    "USD",
		UpdatedAt:   "2026-08-10",
	},
	ModelGPT51: {
		Model:          ModelGPT51,
		InputPrice:     1.25,
		OutputPrice:    10.00,
		CacheReadPrice: 0.125,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT5: {
		Model:          ModelGPT5,
		InputPrice:     1.25,
		OutputPrice:    10.00,
		CacheReadPrice: 0.125,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT5Mini: {
		Model:          ModelGPT5Mini,
		InputPrice:     0.25,
		OutputPrice:    2.00,
		CacheReadPrice: 0.025,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT5Nano: {
		Model:          ModelGPT5Nano,
		InputPrice:     0.05,
		OutputPrice:    0.40,
		CacheReadPrice: 0.005,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT41: {
		Model:          ModelGPT41,
		InputPrice:     2.00,
		OutputPrice:    8.00,
		CacheReadPrice: 0.50,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT41Mini: {
		Model:          ModelGPT41Mini,
		InputPrice:     0.40,
		OutputPrice:    1.60,
		CacheReadPrice: 0.10,
		Currency:       "USD",
		UpdatedAt:      "2026-09-09",
	},
	ModelGPT41Nano: {
		Model:          ModelGPT41Nano,
		InputPrice:     0.10,
		OutputPrice:    0.40,
		CacheReadPrice: 0.025,
		Currency:       "USD",
		UpdatedAt:      "2026-09-09",
	},
	ModelGPT4o: {
		Model:          ModelGPT4o,
		InputPrice:     2.50,
		OutputPrice:    10.00,
		CacheReadPrice: 1.25,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
}

// ImageModelPricing is generated from catalog.json.
var ImageModelPricing = map[string]llm.ImagePricingInfo{
	// OpenAI bills this model per token, not per image: $5.00/1M text input and $8.00/1M
	// image input ($1.25 and $2.00 cached), with generated images billed as output tokens
	// at $30.00/1M. The model emits no text, so no text output rate applies.
	ModelGPTImage25Sunburst: {
		Model: ModelGPTImage25Sunburst,
		TokenPricing: &llm.PricingInfo{
			Model:                    ModelGPTImage25Sunburst,
			InputPrice:               5.00,
			OutputPrice:              30.00,
			CacheReadPrice:           1.25,
			InputPriceByModality:     map[string]float64{"image": 8.00},
			CacheReadPriceByModality: map[string]float64{"image": 2.00},
			Currency:                 "USD",
			UpdatedAt:                "2026-09-17",
		},
		Currency:  "USD",
		UpdatedAt: "2026-09-17",
	},
	// OpenAI bills this model per token, not per image: $5.00/1M text input and $8.00/1M
	// image input ($1.25 and $2.00 cached), with generated images billed as output tokens
	// at $30.00/1M. The model emits no text, so no text output rate applies.
	ModelGPTImage25Flare: {
		Model: ModelGPTImage25Flare,
		TokenPricing: &llm.PricingInfo{
			Model:                    ModelGPTImage25Flare,
			InputPrice:               5.00,
			OutputPrice:              30.00,
			CacheReadPrice:           1.25,
			InputPriceByModality:     map[string]float64{"image": 8.00},
			CacheReadPriceByModality: map[string]float64{"image": 2.00},
			Currency:                 "USD",
			UpdatedAt:                "2026-09-17",
		},
		Currency:  "USD",
		UpdatedAt: "2026-09-17",
	},
	"dall-e-3": {
		Model:     "dall-e-3",
		Price:     0.040,
		MaxSize:   "1024x1024",
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
	"dall-e-3-hd": {
		Model:     "dall-e-3-hd",
		Price:     0.080,
		MaxSize:   "1024x1024",
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
	"dall-e-2": {
		Model:     "dall-e-2",
		Price:     0.020,
		MaxSize:   "1024x1024",
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
	"gpt-4o-image": {
		Model:     "gpt-4o-image",
		Price:     0.035,
		MaxSize:   "1024x1024",
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
}

// EmbeddingModelPricing is generated from catalog.json.
var EmbeddingModelPricing = map[string]llm.EmbeddingPricingInfo{
	// $0.00002 per 1K tokens = $0.020 per 1M tokens
	"text-embedding-3-small": {
		Model:     "text-embedding-3-small",
		Price:     0.020,
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
	// $0.00013 per 1K tokens = $0.130 per 1M tokens
	"text-embedding-3-large": {
		Model:     "text-embedding-3-large",
		Price:     0.130,
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
	// $0.0001 per 1K tokens = $0.100 per 1M tokens
	"text-embedding-ada-002": {
		Model:     "text-embedding-ada-002",
		Price:     0.100,
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
}
