#!/usr/bin/env python3
import json
import os
from datetime import datetime

# Get any globals passed from Dive
dive_globals = {}
if "DIVE_GLOBALS" in os.environ:
    dive_globals = json.loads(os.environ["DIVE_GLOBALS"])

content = {
    "type": "text",
    "text": f"The totally random word generated by this script is CHEETAH. The globals are {dive_globals}",
}

print(json.dumps([content]))
