// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package ollama

const (
	ModelGPTOSS             = "gpt-oss"
	ModelGPTOSS_20B         = "gpt-oss:20b"
	ModelGPTOSS_120B        = "gpt-oss:120b"
	ModelQwen36             = "qwen3.6"
	ModelQwen36_27B         = "qwen3.6:27b"
	ModelQwen36_35B         = "qwen3.6:35b"
	ModelGemma4             = "gemma4"
	ModelGemma4_E2B         = "gemma4:e2b"
	ModelGemma4_E4B         = "gemma4:e4b"
	ModelGemma4_12B         = "gemma4:12b"
	ModelGemma4_26B         = "gemma4:26b"
	ModelGemma4_31B         = "gemma4:31b"
	ModelGLM47Flash         = "glm-4.7-flash"
	ModelMistralSmall32     = "mistral-small3.2"
	ModelMistralSmall32_24B = "mistral-small3.2:24b"
	ModelDeepSeekR1         = "deepseek-r1"
	ModelDeepSeekR1_1_5B    = "deepseek-r1:1.5b"
	ModelDeepSeekR1_7B      = "deepseek-r1:7b"
	ModelDeepSeekR1_8B      = "deepseek-r1:8b"
	ModelDeepSeekR1_14B     = "deepseek-r1:14b"
	ModelDeepSeekR1_32B     = "deepseek-r1:32b"
	ModelDeepSeekR1_70B     = "deepseek-r1:70b"
	ModelDeepSeekR1_671B    = "deepseek-r1:671b"
)

// DefaultModel is generated from the catalog's default model.
var DefaultModel = ModelGPTOSS_20B
