// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package ollama

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{
	// Free - runs locally
	ModelGPTOSS_20B: {
		Model:       ModelGPTOSS_20B,
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2026-08-09",
	},
	ModelGPTOSS_120B: {
		Model:       ModelGPTOSS_120B,
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2026-08-09",
	},
	ModelQwen36_27B: {
		Model:       ModelQwen36_27B,
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2026-08-09",
	},
	ModelQwen36_35B: {
		Model:       ModelQwen36_35B,
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2026-08-09",
	},
	ModelGemma4_E4B: {
		Model:       ModelGemma4_E4B,
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2026-08-09",
	},
	ModelGemma4_12B: {
		Model:       ModelGemma4_12B,
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2026-08-09",
	},
	ModelGLM47Flash: {
		Model:       ModelGLM47Flash,
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2026-08-09",
	},
	ModelDeepSeekR1_8B: {
		Model:       ModelDeepSeekR1_8B,
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2026-08-09",
	},
	ModelDeepSeekR1_32B: {
		Model:       ModelDeepSeekR1_32B,
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2026-08-09",
	},
}

// ImageModelPricing is generated from catalog.json.
var ImageModelPricing = map[string]llm.ImagePricingInfo{}

// EmbeddingModelPricing is generated from catalog.json.
var EmbeddingModelPricing = map[string]llm.EmbeddingPricingInfo{
	// Free - runs locally
	"embeddinggemma": {
		Model:     "embeddinggemma",
		Price:     0.00,
		Currency:  "USD",
		UpdatedAt: "2026-08-09",
	},
	"nomic-embed-text": {
		Model:     "nomic-embed-text",
		Price:     0.00,
		Currency:  "USD",
		UpdatedAt: "2026-08-09",
	},
}
