// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package ollama

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{
	// Free - runs locally
	ModelLlama32_3B: {
		Model:       ModelLlama32_3B,
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2026-08-08",
	},
	// Free - runs locally
	"llama2": {
		Model:       "llama2",
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	"llama2:13b": {
		Model:       "llama2:13b",
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	"llama2:70b": {
		Model:       "llama2:70b",
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	"codellama": {
		Model:       "codellama",
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	"mistral": {
		Model:       "mistral",
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	"neural-chat": {
		Model:       "neural-chat",
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	"starling-lm": {
		Model:       "starling-lm",
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	"orca-mini": {
		Model:       "orca-mini",
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	"vicuna": {
		Model:       "vicuna",
		InputPrice:  0.00,
		OutputPrice: 0.00,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
}

// ImageModelPricing is generated from catalog.json.
var ImageModelPricing = map[string]llm.ImagePricingInfo{}

// EmbeddingModelPricing is generated from catalog.json.
var EmbeddingModelPricing = map[string]llm.EmbeddingPricingInfo{
	// Free - runs locally
	"nomic-embed-text": {
		Model:     "nomic-embed-text",
		Price:     0.00,
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
	"all-minilm": {
		Model:     "all-minilm",
		Price:     0.00,
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
}
