// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package openaicompletions

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{
	// Standard tier. Above 272K input tokens, input, cache read, and
	// cache write rates double and output is 1.5x.
	ModelGPT56: {
		Model:                      ModelGPT56,
		InputPrice:                 4.00,
		OutputPrice:                20.00,
		LongContextInputPrice:      8.00,
		LongContextCacheReadPrice:  0.80,
		LongContextOutputPrice:     30.00,
		CacheReadPrice:             0.40,
		CacheWritePrice:            5.00,
		LongContextCacheWritePrice: 10.00,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-09",
	},
	// Standard tier. Above 272K input tokens, input, cache read, and
	// cache write rates double and output is 1.5x.
	ModelGPT56Sol: {
		Model:                      ModelGPT56Sol,
		InputPrice:                 4.00,
		OutputPrice:                20.00,
		LongContextInputPrice:      8.00,
		LongContextCacheReadPrice:  0.80,
		LongContextOutputPrice:     30.00,
		CacheReadPrice:             0.40,
		CacheWritePrice:            5.00,
		LongContextCacheWritePrice: 10.00,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-09",
	},
	// Standard tier. Above 272K input tokens, input, cache read, and
	// cache write rates double and output is 1.5x.
	ModelGPT56Terra: {
		Model:                      ModelGPT56Terra,
		InputPrice:                 2.00,
		OutputPrice:                12.00,
		LongContextInputPrice:      4.00,
		LongContextCacheReadPrice:  0.40,
		LongContextOutputPrice:     18.00,
		CacheReadPrice:             0.20,
		CacheWritePrice:            2.50,
		LongContextCacheWritePrice: 5.00,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-09",
	},
	// Standard tier. Above 272K input tokens, input, cache read, and
	// cache write rates double and output is 1.5x.
	ModelGPT56Luna: {
		Model:                      ModelGPT56Luna,
		InputPrice:                 0.20,
		OutputPrice:                1.20,
		LongContextInputPrice:      0.40,
		LongContextCacheReadPrice:  0.04,
		LongContextOutputPrice:     1.80,
		CacheReadPrice:             0.02,
		CacheWritePrice:            0.25,
		LongContextCacheWritePrice: 0.50,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-09",
	},
	// Standard tier. Above 272K input tokens, input and cache read
	// double and output is 1.5x.
	ModelGPT55: {
		Model:                     ModelGPT55,
		InputPrice:                5.00,
		OutputPrice:               30.00,
		LongContextInputPrice:     10.00,
		LongContextCacheReadPrice: 1.00,
		LongContextOutputPrice:    45.00,
		CacheReadPrice:            0.50,
		LongContextThreshold:      272001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-09-09",
	},
	// Standard tier. Above 272K input tokens, input and cache read
	// double and output is 1.5x.
	ModelGPT54: {
		Model:                     ModelGPT54,
		InputPrice:                2.50,
		OutputPrice:               15.00,
		LongContextInputPrice:     5.00,
		LongContextCacheReadPrice: 0.50,
		LongContextOutputPrice:    22.50,
		CacheReadPrice:            0.25,
		LongContextThreshold:      272001,
		Currency:                  "USD",
		UpdatedAt:                 "2026-09-09",
	},
	ModelGPT54Mini: {
		Model:          ModelGPT54Mini,
		InputPrice:     0.75,
		OutputPrice:    4.50,
		CacheReadPrice: 0.075,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT54Nano: {
		Model:          ModelGPT54Nano,
		InputPrice:     0.20,
		OutputPrice:    1.25,
		CacheReadPrice: 0.02,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT52: {
		Model:          ModelGPT52,
		InputPrice:     1.75,
		OutputPrice:    14.00,
		CacheReadPrice: 0.175,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT51: {
		Model:          ModelGPT51,
		InputPrice:     1.25,
		OutputPrice:    10.00,
		CacheReadPrice: 0.125,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT5: {
		Model:          ModelGPT5,
		InputPrice:     1.25,
		OutputPrice:    10.00,
		CacheReadPrice: 0.125,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT5Mini: {
		Model:          ModelGPT5Mini,
		InputPrice:     0.25,
		OutputPrice:    2.00,
		CacheReadPrice: 0.025,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT5Nano: {
		Model:          ModelGPT5Nano,
		InputPrice:     0.05,
		OutputPrice:    0.40,
		CacheReadPrice: 0.005,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT41: {
		Model:          ModelGPT41,
		InputPrice:     2.00,
		OutputPrice:    8.00,
		CacheReadPrice: 0.50,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGPT41Mini: {
		Model:          ModelGPT41Mini,
		InputPrice:     0.40,
		OutputPrice:    1.60,
		CacheReadPrice: 0.10,
		Currency:       "USD",
		UpdatedAt:      "2026-09-09",
	},
	ModelGPT41Nano: {
		Model:          ModelGPT41Nano,
		InputPrice:     0.10,
		OutputPrice:    0.40,
		CacheReadPrice: 0.025,
		Currency:       "USD",
		UpdatedAt:      "2026-09-09",
	},
	ModelGPT4o: {
		Model:          ModelGPT4o,
		InputPrice:     2.50,
		OutputPrice:    10.00,
		CacheReadPrice: 1.25,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
}
