// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package mistral

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{
	ModelMistralMedium: {
		Model:       ModelMistralMedium,
		InputPrice:  1.5,
		OutputPrice: 7.5,
		Currency:    "USD",
		UpdatedAt:   "2026-08-15",
	},
	ModelMistralLarge2411: {
		Model:       ModelMistralLarge2411,
		InputPrice:  2.0,
		OutputPrice: 6.0,
		Currency:    "USD",
		UpdatedAt:   "2025-10-15",
	},
	ModelMistralLarge: {
		Model:       ModelMistralLarge,
		InputPrice:  0.5,
		OutputPrice: 1.5,
		Currency:    "USD",
		UpdatedAt:   "2026-08-15",
	},
	ModelMistralSmall: {
		Model:       ModelMistralSmall,
		InputPrice:  0.15,
		OutputPrice: 0.6,
		Currency:    "USD",
		UpdatedAt:   "2026-08-15",
	},
	ModelCodestralLatest: {
		Model:       ModelCodestralLatest,
		InputPrice:  0.3,
		OutputPrice: 0.9,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelCodestral2501: {
		Model:       ModelCodestral2501,
		InputPrice:  0.3,
		OutputPrice: 0.9,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelMistral7B: {
		Model:       ModelMistral7B,
		InputPrice:  0.25,
		OutputPrice: 0.25,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelMixtral8x7B: {
		Model:       ModelMixtral8x7B,
		InputPrice:  0.7,
		OutputPrice: 0.7,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelMixtral8x22B: {
		Model:       ModelMixtral8x22B,
		InputPrice:  2.0,
		OutputPrice: 6.0,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelCodestralMamba: {
		Model:       ModelCodestralMamba,
		InputPrice:  0.25,
		OutputPrice: 0.25,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
}

// ImageModelPricing is generated from catalog.json.
var ImageModelPricing = map[string]ImagePricingInfo{}

// EmbeddingModelPricing is generated from catalog.json.
var EmbeddingModelPricing = map[string]EmbeddingPricingInfo{}
