// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package mistral

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{
	ModelMistralMedium: {
		Model:       ModelMistralMedium,
		InputPrice:  1.5,
		OutputPrice: 7.5,
		Currency:    "USD",
		UpdatedAt:   "2026-08-15",
	},
	ModelMistralLarge2411: {
		Model:       ModelMistralLarge2411,
		InputPrice:  2.0,
		OutputPrice: 6.0,
		Currency:    "USD",
		UpdatedAt:   "2025-10-15",
	},
	ModelMistralLarge: {
		Model:       ModelMistralLarge,
		InputPrice:  0.5,
		OutputPrice: 1.5,
		Currency:    "USD",
		UpdatedAt:   "2026-08-15",
	},
	ModelMistralSmall: {
		Model:       ModelMistralSmall,
		InputPrice:  0.15,
		OutputPrice: 0.6,
		Currency:    "USD",
		UpdatedAt:   "2026-08-15",
	},
	ModelGLM52: {
		Model:          ModelGLM52,
		InputPrice:     1.4,
		OutputPrice:    4.4,
		CacheReadPrice: 0.14,
		Currency:       "USD",
		UpdatedAt:      "2026-09-09",
	},
	// Alias of glm-5-2; Mistral's pricing page lists this id.
	ModelGLM52ZAI: {
		Model:          ModelGLM52ZAI,
		InputPrice:     1.4,
		OutputPrice:    4.4,
		CacheReadPrice: 0.14,
		Currency:       "USD",
		UpdatedAt:      "2026-09-09",
	},
	// Alias of mistral-medium-latest.
	ModelMagistralMedium: {
		Model:       ModelMagistralMedium,
		InputPrice:  1.5,
		OutputPrice: 7.5,
		Currency:    "USD",
		UpdatedAt:   "2026-09-09",
	},
	// Alias of mistral-small-latest.
	ModelMagistralSmall: {
		Model:       ModelMagistralSmall,
		InputPrice:  0.15,
		OutputPrice: 0.6,
		Currency:    "USD",
		UpdatedAt:   "2026-09-09",
	},
	ModelMistralSmall2603: {
		Model:       ModelMistralSmall2603,
		InputPrice:  0.15,
		OutputPrice: 0.6,
		Currency:    "USD",
		UpdatedAt:   "2026-09-09",
	},
	ModelMinistral3_14BLatest: {
		Model:       ModelMinistral3_14BLatest,
		InputPrice:  0.2,
		OutputPrice: 0.2,
		Currency:    "USD",
		UpdatedAt:   "2026-09-09",
	},
	ModelMinistral3_14B: {
		Model:       ModelMinistral3_14B,
		InputPrice:  0.2,
		OutputPrice: 0.2,
		Currency:    "USD",
		UpdatedAt:   "2026-09-09",
	},
	ModelMinistral3_8BLatest: {
		Model:       ModelMinistral3_8BLatest,
		InputPrice:  0.15,
		OutputPrice: 0.15,
		Currency:    "USD",
		UpdatedAt:   "2026-09-09",
	},
	ModelMinistral3_8B: {
		Model:       ModelMinistral3_8B,
		InputPrice:  0.15,
		OutputPrice: 0.15,
		Currency:    "USD",
		UpdatedAt:   "2026-09-09",
	},
	ModelMinistral3_3BLatest: {
		Model:       ModelMinistral3_3BLatest,
		InputPrice:  0.1,
		OutputPrice: 0.1,
		Currency:    "USD",
		UpdatedAt:   "2026-09-09",
	},
	ModelMinistral3_3B: {
		Model:       ModelMinistral3_3B,
		InputPrice:  0.1,
		OutputPrice: 0.1,
		Currency:    "USD",
		UpdatedAt:   "2026-09-09",
	},
	ModelCodestralLatest: {
		Model:       ModelCodestralLatest,
		InputPrice:  0.3,
		OutputPrice: 0.9,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelCodestral2501: {
		Model:       ModelCodestral2501,
		InputPrice:  0.3,
		OutputPrice: 0.9,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelMistral7B: {
		Model:       ModelMistral7B,
		InputPrice:  0.25,
		OutputPrice: 0.25,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelMixtral8x7B: {
		Model:       ModelMixtral8x7B,
		InputPrice:  0.7,
		OutputPrice: 0.7,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelMixtral8x22B: {
		Model:       ModelMixtral8x22B,
		InputPrice:  2.0,
		OutputPrice: 6.0,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
	ModelCodestralMamba: {
		Model:       ModelCodestralMamba,
		InputPrice:  0.25,
		OutputPrice: 0.25,
		Currency:    "USD",
		UpdatedAt:   "2025-01-15",
	},
}

// ImageModelPricing is generated from catalog.json.
var ImageModelPricing = map[string]llm.ImagePricingInfo{}

// EmbeddingModelPricing is generated from catalog.json.
var EmbeddingModelPricing = map[string]llm.EmbeddingPricingInfo{}
