package compaction

// Live capture harness: runs each testdata fixture through real compaction
// against an Anthropic model and writes the raw compaction output to
// testdata/captured/<name>.md for human review. Each file is exactly the
// compacted message that becomes the new active window — the handoff-framed
// summary the next turn receives — with no added scaffolding. Per-run stats
// (token reduction, etc.) live in captured/README.md.
//
// This is opt-in and never runs during a normal `go test ./...`: it requires
// both ANTHROPIC_API_KEY and CAPTURE_COMPACTION=1, because it makes paid
// network calls. Regenerate the captures with:
//
//	CAPTURE_COMPACTION=1 \
//	  go test ./experimental/compaction -run TestCaptureCompactionOutputs -v
//
// Override the summarizer model with DIVE_COMPACTION_MODEL (default
// claude-haiku-4-5 — compaction is a good fit for a fast, cheap model).

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/deepnoodle-ai/dive/llm"
	"github.com/deepnoodle-ai/dive/providers/anthropic"
	"github.com/deepnoodle-ai/dive/session"
	"github.com/deepnoodle-ai/wonton/assert"
)

const defaultCaptureModel = "claude-haiku-4-5"

func TestCaptureCompactionOutputs(t *testing.T) {
	if os.Getenv("CAPTURE_COMPACTION") != "1" {
		t.Skip("set CAPTURE_COMPACTION=1 (and ANTHROPIC_API_KEY) to capture live compaction outputs")
	}
	if os.Getenv("ANTHROPIC_API_KEY") == "" {
		t.Skip("ANTHROPIC_API_KEY not set")
	}

	modelName := os.Getenv("DIVE_COMPACTION_MODEL")
	if modelName == "" {
		modelName = defaultCaptureModel
	}
	model := anthropic.New(anthropic.WithModel(modelName))

	outDir := filepath.Join("testdata", "captured")
	assert.NoError(t, os.MkdirAll(outDir, 0o755))

	type row struct {
		name                      string
		msgsBefore                int
		tokensBefore, tokensAfter int
		elapsed                   time.Duration
	}
	var rows []row

	for _, f := range loadFixtures(t) {
		t.Run(f.name, func(t *testing.T) {
			ctx, cancel := context.WithTimeout(context.Background(), 3*time.Minute)
			defer cancel()

			sess := session.New(f.name)
			assert.NoError(t, sess.SaveTurn(ctx, f.messages, nil))

			before, err := sess.Messages(ctx)
			assert.NoError(t, err)
			tokensBefore := activeTokens(before)

			var event *CompactionEvent
			start := time.Now()
			err = sess.Compact(ctx, func(ctx context.Context, msgs []*llm.Message) ([]*llm.Message, error) {
				out, ev, cerr := CompactMessages(ctx, model, msgs, "", "", tokensBefore)
				event = ev
				return out, cerr
			})
			elapsed := time.Since(start)
			assert.NoError(t, err)
			assert.NotNil(t, event)

			after, err := sess.Messages(ctx)
			assert.NoError(t, err)
			assert.Len(t, after, 1) // active window is now the single summary
			tokensAfter := activeTokens(after)

			// Non-destructive invariants: full transcript retained, one checkpoint.
			all, err := sess.AllMessages(ctx)
			assert.NoError(t, err)
			assert.Equal(t, len(before)+1, len(all))
			hist, err := sess.CompactionHistory(ctx)
			assert.NoError(t, err)
			assert.Len(t, hist, 1)

			// Write the raw compaction output verbatim — the compacted message
			// exactly as the next turn will receive it.
			path := filepath.Join(outDir, f.name+".md")
			assert.NoError(t, os.WriteFile(path, []byte(after[0].Text()+"\n"), 0o644))
			t.Logf("wrote %s — active window %d→%d tokens (%.0f%% smaller) in %s",
				path, tokensBefore, tokensAfter, reductionPct(tokensBefore, tokensAfter), elapsed.Round(time.Millisecond))

			rows = append(rows, row{f.name, len(before), tokensBefore, tokensAfter, elapsed})
		})
	}

	// Index for the captured/ directory: per-run stats, pointing at the raw
	// output files.
	var idx strings.Builder
	fmt.Fprintf(&idx, "# Captured compaction outputs\n\n")
	fmt.Fprintf(&idx, "Each `<scenario>.md` is the **raw compaction output** — the compacted message\n")
	fmt.Fprintf(&idx, "(handoff-framed summary) that becomes the new active window, exactly as the\n")
	fmt.Fprintf(&idx, "next turn receives it. Generated by `TestCaptureCompactionOutputs` (model\n")
	fmt.Fprintf(&idx, "`%s`). Token estimates are JSON bytes ÷ 4.\n\n", modelName)
	fmt.Fprintf(&idx, "| Scenario | Active window before | After | Reduction |\n")
	fmt.Fprintf(&idx, "|---|---|---|---|\n")
	for _, r := range rows {
		fmt.Fprintf(&idx, "| [%s](%s.md) | %d msgs / ~%s tok | 1 msg / ~%s tok | %.0f%% |\n",
			r.name, r.name, r.msgsBefore, withCommas(r.tokensBefore), withCommas(r.tokensAfter),
			reductionPct(r.tokensBefore, r.tokensAfter))
	}
	assert.NoError(t, os.WriteFile(filepath.Join(outDir, "README.md"), []byte(idx.String()), 0o644))
}

func reductionPct(before, after int) float64 {
	if before <= 0 {
		return 0
	}
	return float64(before-after) / float64(before) * 100
}

// withCommas formats an int with thousands separators (e.g. 12345 -> "12,345").
func withCommas(n int) string {
	s := fmt.Sprintf("%d", n)
	if len(s) <= 3 {
		return s
	}
	var parts []string
	for len(s) > 3 {
		parts = append([]string{s[len(s)-3:]}, parts...)
		s = s[:len(s)-3]
	}
	parts = append([]string{s}, parts...)
	return strings.Join(parts, ",")
}
