// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package grok

const (
	ModelGrok45                 = "grok-4.5"
	ModelGrok43                 = "grok-4.3"
	ModelGrok420Reasoning       = "grok-4.20-0309-reasoning"
	ModelGrok420NonReasoning    = "grok-4.20-0309-non-reasoning"
	ModelGrok420MultiAgent      = "grok-4.20-multi-agent-0309"
	ModelGrokBuild01            = "grok-build-0.1"
	ModelGrok41FastReasoning    = "grok-4-1-fast-reasoning"
	ModelGrok41FastNonReasoning = "grok-4-1-fast-non-reasoning"
	ModelGrok4FastReasoning     = "grok-4-fast-reasoning"
	ModelGrok4FastNonReasoning  = "grok-4-fast-non-reasoning"
	ModelGrok40709              = "grok-4-0709"
	ModelGrok4                  = "grok-4"
	ModelGrok4Latest            = "grok-4-latest"
	ModelGrok3                  = "grok-3"
	ModelGrok3Latest            = "grok-3-latest"
	ModelGrok3Mini              = "grok-3-mini"
	ModelGrokCodeFast1          = "grok-code-fast-1"
	ModelImagineImagePro        = "grok-imagine-image-pro"
	ModelImagineImage           = "grok-imagine-image"
	ModelImagineImageQuality    = "grok-imagine-image-quality"
	ModelImagineVideo           = "grok-imagine-video"
)

// DefaultModel is generated from the catalog's default model.
var DefaultModel = ModelGrok45
