// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package grok

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{
	ModelGrok46: {
		Model:                     ModelGrok46,
		InputPrice:                2.00,
		OutputPrice:               6.00,
		LongContextInputPrice:     4.00,
		LongContextCacheReadPrice: 1.00,
		LongContextOutputPrice:    12.00,
		CacheReadPrice:            0.50,
		LongContextThreshold:      200000,
		Currency:                  "USD",
		UpdatedAt:                 "2026-08-12",
	},
	ModelGrok45: {
		Model:                     ModelGrok45,
		InputPrice:                2.00,
		OutputPrice:               6.00,
		LongContextInputPrice:     4.00,
		LongContextCacheReadPrice: 0.60,
		LongContextOutputPrice:    12.00,
		CacheReadPrice:            0.30,
		LongContextThreshold:      200000,
		Currency:                  "USD",
		UpdatedAt:                 "2026-08-10",
	},
	ModelGrok43: {
		Model:                     ModelGrok43,
		InputPrice:                1.25,
		OutputPrice:               2.50,
		LongContextInputPrice:     2.50,
		LongContextCacheReadPrice: 0.40,
		LongContextOutputPrice:    5.00,
		CacheReadPrice:            0.20,
		LongContextThreshold:      200000,
		Currency:                  "USD",
		UpdatedAt:                 "2026-08-10",
	},
	ModelGrok420Reasoning: {
		Model:                     ModelGrok420Reasoning,
		InputPrice:                1.25,
		OutputPrice:               2.50,
		LongContextInputPrice:     2.50,
		LongContextCacheReadPrice: 0.40,
		LongContextOutputPrice:    5.00,
		CacheReadPrice:            0.20,
		LongContextThreshold:      200000,
		Currency:                  "USD",
		UpdatedAt:                 "2026-08-10",
	},
	ModelGrok420NonReasoning: {
		Model:                     ModelGrok420NonReasoning,
		InputPrice:                1.25,
		OutputPrice:               2.50,
		LongContextInputPrice:     2.50,
		LongContextCacheReadPrice: 0.40,
		LongContextOutputPrice:    5.00,
		CacheReadPrice:            0.20,
		LongContextThreshold:      200000,
		Currency:                  "USD",
		UpdatedAt:                 "2026-08-10",
	},
	ModelGrok420MultiAgent: {
		Model:                     ModelGrok420MultiAgent,
		InputPrice:                1.25,
		OutputPrice:               2.50,
		LongContextInputPrice:     2.50,
		LongContextCacheReadPrice: 0.40,
		LongContextOutputPrice:    5.00,
		CacheReadPrice:            0.20,
		LongContextThreshold:      200000,
		Currency:                  "USD",
		UpdatedAt:                 "2026-08-10",
	},
	ModelGrokBuild01: {
		Model:                     ModelGrokBuild01,
		InputPrice:                1.00,
		OutputPrice:               2.00,
		LongContextInputPrice:     2.00,
		LongContextCacheReadPrice: 0.40,
		LongContextOutputPrice:    4.00,
		CacheReadPrice:            0.20,
		LongContextThreshold:      200000,
		Currency:                  "USD",
		UpdatedAt:                 "2026-08-10",
	},
	// Retired slug; requests are served by grok-4.3 and billed at its rates.
	ModelGrok41FastReasoning: {
		Model:          ModelGrok41FastReasoning,
		InputPrice:     1.25,
		OutputPrice:    2.50,
		CacheReadPrice: 0.20,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	// Retired slug; requests are served by grok-4.3 and billed at its rates.
	ModelGrok41FastNonReasoning: {
		Model:          ModelGrok41FastNonReasoning,
		InputPrice:     1.25,
		OutputPrice:    2.50,
		CacheReadPrice: 0.20,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	// Retired slug; requests are served by grok-4.3 and billed at its rates.
	ModelGrok4FastReasoning: {
		Model:          ModelGrok4FastReasoning,
		InputPrice:     1.25,
		OutputPrice:    2.50,
		CacheReadPrice: 0.20,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	// Retired slug; requests are served by grok-4.3 and billed at its rates.
	ModelGrok4FastNonReasoning: {
		Model:          ModelGrok4FastNonReasoning,
		InputPrice:     1.25,
		OutputPrice:    2.50,
		CacheReadPrice: 0.20,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	// Retired slug; requests are served by grok-4.3 and billed at its rates.
	ModelGrok40709: {
		Model:          ModelGrok40709,
		InputPrice:     1.25,
		OutputPrice:    2.50,
		CacheReadPrice: 0.20,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	// Retired slug; requests are served by grok-build-0.1 and billed at its rates.
	ModelGrokCodeFast1: {
		Model:          ModelGrokCodeFast1,
		InputPrice:     1.00,
		OutputPrice:    2.00,
		CacheReadPrice: 0.20,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	// Retired slug; requests are served by grok-4.3 and billed at its rates.
	ModelGrok3: {
		Model:          ModelGrok3,
		InputPrice:     1.25,
		OutputPrice:    2.50,
		CacheReadPrice: 0.20,
		Currency:       "USD",
		UpdatedAt:      "2026-08-10",
	},
	ModelGrok3Mini: {
		Model:       ModelGrok3Mini,
		InputPrice:  0.30,
		OutputPrice: 0.50,
		Currency:    "USD",
		UpdatedAt:   "2026-02-09",
	},
}

// ImageModelPricing is generated from catalog.json.
var ImageModelPricing = map[string]llm.ImagePricingInfo{
	ModelImagineImage: {
		Model:     ModelImagineImage,
		Price:     0.02,
		Currency:  "USD",
		UpdatedAt: "2026-05-28",
	},
	ModelImagineImageQuality: {
		Model:     ModelImagineImageQuality,
		Price:     0.05,
		Currency:  "USD",
		UpdatedAt: "2026-05-28",
	},
	ModelImagineImage20: {
		Model:     ModelImagineImage20,
		Price:     0.04,
		Currency:  "USD",
		UpdatedAt: "2026-08-12",
	},
}
