#!/usr/bin/env python3
"""Generate provider Go constants and pricing tables from catalog.json files."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
import datetime as dt
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
from typing import Any, Iterable, Mapping, Sequence


REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATED_HEADER = "// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT."
GO_NAME_RE = re.compile(r"^Model[A-Za-z0-9_]+$")
FEATURE_NAME_RE = re.compile(r"^Feature[A-Za-z0-9_]+$")
DECIMAL_RE = re.compile(r"^(?:0|[1-9]\d*)(?:\.\d+)?$")
GO_TYPE_IMPORTS = {
    "openaisdk.ChatModel": 'openaisdk "github.com/openai/openai-go/v3"',
}
GOFMT = shutil.which("gofmt")


@dataclass(frozen=True)
class Table:
    json_name: str
    go_name: str
    go_type: str
    kind: str


@dataclass(frozen=True)
class Target:
    name: str
    package: str
    directory: Path
    source_provider: str
    tables: tuple[Table, ...]
    embed: bool = True
    adapter: str | None = None
    generate_default: bool = True


LLM_TEXT = "llm.PricingInfo"
LLM_IMAGE = "llm.ImagePricingInfo"
LLM_EMBEDDING = "llm.EmbeddingPricingInfo"

TEXT = Table("text", "TextModelPricing", LLM_TEXT, "text")
FAST_TEXT = Table("fast_text", "FastModeTextPricing", LLM_TEXT, "text")
IMAGE = Table("image", "ImageModelPricing", LLM_IMAGE, "image")
EMBEDDING = Table("embedding", "EmbeddingModelPricing", LLM_EMBEDDING, "embedding")

TARGETS: dict[str, Target] = {
    "anthropic": Target(
        "anthropic",
        "anthropic",
        REPO_ROOT / "providers" / "anthropic",
        "anthropic",
        (TEXT, FAST_TEXT),
    ),
    "google": Target(
        "google",
        "google",
        REPO_ROOT / "providers" / "google",
        "google",
        (TEXT, IMAGE, EMBEDDING),
    ),
    "grok": Target(
        "grok",
        "grok",
        REPO_ROOT / "providers" / "grok",
        "grok",
        (TEXT, IMAGE),
    ),
    "mistral": Target(
        "mistral",
        "mistral",
        REPO_ROOT / "providers" / "mistral",
        "mistral",
        (
            TEXT,
            Table("image", "ImageModelPricing", "ImagePricingInfo", "image"),
            Table(
                "embedding",
                "EmbeddingModelPricing",
                "EmbeddingPricingInfo",
                "embedding",
            ),
        ),
    ),
    "ollama": Target(
        "ollama",
        "ollama",
        REPO_ROOT / "providers" / "ollama",
        "ollama",
        (TEXT, IMAGE, EMBEDDING),
    ),
    "openai": Target(
        "openai",
        "openai",
        REPO_ROOT / "providers" / "openai",
        "openai",
        (TEXT, IMAGE, EMBEDDING),
    ),
    "openrouter": Target(
        "openrouter",
        "openrouter",
        REPO_ROOT / "providers" / "openrouter",
        "openrouter",
        (TEXT, IMAGE, EMBEDDING),
    ),
    "openaicompletions": Target(
        "openaicompletions",
        "openaicompletions",
        REPO_ROOT / "providers" / "openaicompletions",
        "openai",
        (TEXT,),
        embed=False,
        adapter="openaicompletions",
        generate_default=False,
    ),
}


class CatalogError(ValueError):
    pass


def read_catalog(provider: str) -> dict[str, Any]:
    path = REPO_ROOT / "providers" / provider / "catalog.json"
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as error:
        raise CatalogError(f"failed to read {path}: {error}") from error
    validate_catalog(value, provider, path)
    return value


def validate_catalog(catalog: Mapping[str, Any], provider: str, path: Path) -> None:
    allowed = {
        "schema_version",
        "provider",
        "sources",
        "models",
        "pricing",
        "feature_flags",
    }
    unknown = set(catalog) - allowed
    if unknown:
        raise CatalogError(f"{path}: unknown top-level fields: {sorted(unknown)}")
    if catalog.get("schema_version") != 1:
        raise CatalogError(f"{path}: schema_version must be 1")
    if catalog.get("provider") != provider:
        raise CatalogError(f"{path}: provider must be {provider!r}")

    models = catalog.get("models")
    if not isinstance(models, list) or not models:
        raise CatalogError(f"{path}: models must be a non-empty list")
    names: set[str] = set()
    ids: set[str] = set()
    defaults = 0
    for model in models:
        if not isinstance(model, dict):
            raise CatalogError(f"{path}: model entries must be objects")
        go_name = model.get("go_name", "")
        model_id = model.get("id", "")
        alias_of = model.get("alias_of", "")
        if not GO_NAME_RE.fullmatch(go_name):
            raise CatalogError(f"{path}: invalid go_name {go_name!r}")
        if model.get("go_type") and model["go_type"] not in GO_TYPE_IMPORTS:
            raise CatalogError(
                f"{path}: {go_name} has unsupported go_type {model['go_type']!r}"
            )
        if go_name in names:
            raise CatalogError(f"{path}: duplicate go_name {go_name!r}")
        if bool(model_id) == bool(alias_of):
            raise CatalogError(
                f"{path}: {go_name} must set exactly one of id or alias_of"
            )
        if model_id and model_id in ids:
            raise CatalogError(f"{path}: duplicate model id {model_id!r}")
        names.add(go_name)
        if model_id:
            ids.add(model_id)
        defaults += int(bool(model.get("default")))
    if defaults != 1:
        raise CatalogError(f"{path}: exactly one model must be default")
    for model in models:
        alias_of = model.get("alias_of")
        if alias_of and alias_of not in names:
            raise CatalogError(f"{path}: {model['go_name']} aliases unknown {alias_of}")

    pricing = catalog.get("pricing", {})
    if not isinstance(pricing, dict):
        raise CatalogError(f"{path}: pricing must be an object")
    if set(pricing) - {
        "text",
        "fast_text",
        "image",
        "embedding",
    }:
        raise CatalogError(f"{path}: unknown pricing table")
    for table_name, entries in pricing.items():
        if not isinstance(entries, list):
            raise CatalogError(f"{path}: {table_name} must be a list")
        seen: set[str] = set()
        for entry in entries:
            if not isinstance(entry, dict):
                raise CatalogError(f"{path}: {table_name} entries must be objects")
            model_id = entry.get("model", "")
            if not model_id or model_id in seen:
                raise CatalogError(
                    f"{path}: {table_name} has missing or duplicate model {model_id!r}"
                )
            seen.add(model_id)
            if table_name in {"text", "fast_text"}:
                price_fields = (
                    "input_price_per_1m_tokens",
                    "output_price_per_1m_tokens",
                )
                # Optional, but still interpolated into Go source unquoted.
                optional_price_fields = (
                    "long_context_input_price_per_1m_tokens",
                    "long_context_cache_read_price_per_1m_tokens",
                    "long_context_output_price_per_1m_tokens",
                    "cache_read_price_per_1m_tokens",
                    "cache_read_price_above_threshold_per_1m_tokens",
                    "cache_write_price_per_1m_tokens",
                    "non_global_price_multiplier",
                )
            elif table_name == "image":
                price_fields = ("price_per_image",)
                optional_price_fields = ()
            else:
                price_fields = ("price_per_1m_tokens",)
                optional_price_fields = ()
            for field in price_fields:
                value = entry.get(field)
                if not isinstance(value, str) or not DECIMAL_RE.fullmatch(value):
                    raise CatalogError(
                        f"{path}: {table_name}/{model_id} has invalid {field}"
                    )
            for field in optional_price_fields:
                value = entry.get(field)
                if value in (None, ""):
                    continue
                if not isinstance(value, str) or not DECIMAL_RE.fullmatch(value):
                    raise CatalogError(
                        f"{path}: {table_name}/{model_id} has invalid {field}"
                    )
            if table_name in {"text", "fast_text"}:
                for field in (
                    "input_price_per_1m_tokens_by_modality",
                    "output_price_per_1m_tokens_by_modality",
                    "cache_read_price_per_1m_tokens_by_modality",
                ):
                    values = entry.get(field)
                    if values is None:
                        continue
                    if not isinstance(values, dict) or not values:
                        raise CatalogError(
                            f"{path}: {table_name}/{model_id} has invalid {field}"
                        )
                    for modality, value in values.items():
                        if (
                            not isinstance(modality, str)
                            or not modality
                            or modality.lower() != modality
                            or not isinstance(value, str)
                            or not DECIMAL_RE.fullmatch(value)
                        ):
                            raise CatalogError(
                                f"{path}: {table_name}/{model_id} has invalid {field}/{modality}"
                            )
                cache_threshold = entry.get("cache_read_price_threshold_tokens")
                cache_above = entry.get(
                    "cache_read_price_above_threshold_per_1m_tokens"
                )
                if bool(cache_threshold) != bool(cache_above) or (
                    cache_threshold is not None
                    and (not isinstance(cache_threshold, int) or cache_threshold <= 0)
                ):
                    raise CatalogError(
                        f"{path}: {table_name}/{model_id} has incomplete cache-read threshold pricing"
                    )
                long_threshold = entry.get("long_context_threshold_tokens")
                long_prices = tuple(
                    entry.get(field)
                    for field in (
                        "long_context_input_price_per_1m_tokens",
                        "long_context_cache_read_price_per_1m_tokens",
                        "long_context_output_price_per_1m_tokens",
                    )
                )
                if bool(long_threshold) != any(long_prices) or (
                    long_threshold is not None
                    and (not isinstance(long_threshold, int) or long_threshold <= 0)
                ) or (long_threshold and not all(long_prices)):
                    raise CatalogError(
                        f"{path}: {table_name}/{model_id} has incomplete long-context pricing"
                    )
                multiplier = entry.get("non_global_price_multiplier")
                if multiplier is not None and float(multiplier) <= 0:
                    raise CatalogError(
                        f"{path}: {table_name}/{model_id} has invalid non_global_price_multiplier"
                    )
            for field in ("currency", "updated_at"):
                value = entry.get(field)
                if not isinstance(value, str) or not value:
                    raise CatalogError(
                        f"{path}: {table_name}/{model_id} has invalid {field}"
                    )
            if not re.fullmatch(r"[A-Z]{3}", entry["currency"]):
                raise CatalogError(
                    f"{path}: {table_name}/{model_id} has invalid currency"
                )
            if not re.fullmatch(r"\d{4}-\d{2}-\d{2}", entry["updated_at"]):
                raise CatalogError(
                    f"{path}: {table_name}/{model_id} has invalid updated_at"
                )
            try:
                dt.date.fromisoformat(entry["updated_at"])
            except ValueError as error:
                raise CatalogError(
                    f"{path}: {table_name}/{model_id} has invalid updated_at"
                ) from error

    validate_features(catalog.get("feature_flags") or [], path)


def validate_features(features: Any, path: Path) -> None:
    """Check what this script turns into Go source.

    providers/modelcatalog applies the full schema at parse time, and
    catalog_disk_test.go runs it against every checked-in catalog, so this
    covers the fields that would otherwise crash generation or emit bad Go.
    """

    if not isinstance(features, list):
        raise CatalogError(f"{path}: feature_flags must be a list")
    names: set[str] = set()
    ids: set[str] = set()
    aliases: dict[str, str] = {}
    for feature in features:
        if not isinstance(feature, dict):
            raise CatalogError(f"{path}: feature_flags entries must be objects")
        go_name = feature.get("go_name", "")
        if not FEATURE_NAME_RE.fullmatch(go_name):
            raise CatalogError(f"{path}: invalid feature go_name {go_name!r}")
        if go_name in names:
            raise CatalogError(f"{path}: duplicate feature go_name {go_name!r}")
        names.add(go_name)
        feature_id = feature.get("id", "")
        alias_of = feature.get("alias_of", "")
        if bool(feature_id) == bool(alias_of):
            raise CatalogError(
                f"{path}: {go_name} must set exactly one of id or alias_of"
            )
        if feature_id:
            if feature_id in ids:
                raise CatalogError(f"{path}: duplicate feature flag {feature_id!r}")
            ids.add(feature_id)
        else:
            aliases[go_name] = alias_of
    for go_name, alias_of in aliases.items():
        if alias_of not in names:
            raise CatalogError(f"{path}: {go_name} aliases unknown {alias_of}")
        if alias_of in aliases:
            raise CatalogError(f"{path}: {go_name} aliases another alias {alias_of}")


def go_string(value: str) -> str:
    return json.dumps(value, ensure_ascii=False)


def comment_lines(value: str, prefix: str = "// ") -> list[str]:
    return [prefix + line for line in value.splitlines() if line.strip()]


def target_models(target: Target, catalog: Mapping[str, Any]) -> list[Mapping[str, Any]]:
    models = list(catalog["models"])
    if not target.adapter:
        return models
    return [model for model in models if target.adapter in model.get("adapters", [])]


def render_models(target: Target, catalog: Mapping[str, Any]) -> str:
    models = target_models(target, catalog)
    included_names = {model["go_name"] for model in models}
    lines = [GENERATED_HEADER, "", f"package {target.package}"]
    go_types = {
        model.get("go_type")
        for model in models
        if target.embed and model.get("go_type")
    }
    if go_types:
        imports = [GO_TYPE_IMPORTS[go_type] for go_type in sorted(go_types)]
        lines.extend(("", "import (", *(f"\t{item}" for item in imports), ")"))
    lines.extend(("", "const ("))
    for model in models:
        deprecated = model.get("deprecated")
        if deprecated:
            lines.extend(f"\t{line}" for line in comment_lines(f"Deprecated: {deprecated}"))
        go_name = model["go_name"]
        if model.get("alias_of"):
            target_name = model["alias_of"]
            if target_name not in included_names:
                raise CatalogError(
                    f"{target.name}: {go_name} aliases {target_name}, which is not exported"
                )
            value = target_name
        else:
            value = go_string(model["id"])
        go_type = model.get("go_type", "") if target.embed else ""
        declaration = f"{go_name} {go_type}" if go_type else go_name
        lines.append(f"\t{declaration} = {value}")
    lines.extend((")", ""))
    if target.generate_default:
        default = next((model for model in models if model.get("default")), None)
        if default is None:
            raise CatalogError(
                f"{target.name}: no default model after adapter filtering"
            )
        lines.extend(
            (
                "// DefaultModel is generated from the catalog's default model.",
                f"var DefaultModel = {default['go_name']}",
                "",
            )
        )
    return "\n".join(lines)


def render_catalog_embed(target: Target) -> str:
    return "\n".join(
        (
            GENERATED_HEADER,
            "",
            f"package {target.package}",
            "",
            "import (",
            '\t"bytes"',
            '\t_ "embed"',
            "",
            '\t"github.com/deepnoodle-ai/dive/providers/modelcatalog"',
            ")",
            "",
            "//go:embed catalog.json",
            "var embeddedCatalogJSON []byte",
            "",
            f'var embeddedCatalog = modelcatalog.MustParse("{target.source_provider}", embeddedCatalogJSON)',
            "",
            "// Catalog returns a copy of this provider's embedded model catalog.",
            "func Catalog() modelcatalog.Catalog {",
            "\treturn embeddedCatalog.Clone()",
            "}",
            "",
            "// CatalogJSON returns a copy of the canonical embedded catalog document.",
            "func CatalogJSON() []byte {",
            "\treturn bytes.Clone(embeddedCatalogJSON)",
            "}",
            "",
        )
    )


def render_features(target: Target, catalog: Mapping[str, Any]) -> str | None:
    features = list(catalog.get("feature_flags") or [])
    if not features:
        return None
    lines = [GENERATED_HEADER, "", f"package {target.package}", "", "const ("]
    included = {feature["go_name"] for feature in features}
    for feature in features:
        deprecated = feature.get("deprecated")
        if deprecated:
            lines.extend(f"\t{line}" for line in comment_lines(f"Deprecated: {deprecated}"))
        go_name = feature["go_name"]
        if feature.get("alias_of"):
            alias = feature["alias_of"]
            if alias not in included:
                raise CatalogError(f"{target.name}: {go_name} aliases unknown {alias}")
            value = alias
        else:
            value = go_string(feature["id"])
        lines.append(f"\t{go_name} = {value}")
    lines.extend((")", ""))
    return "\n".join(lines)


def model_constant_by_id(
    target: Target, catalog: Mapping[str, Any]
) -> dict[str, str]:
    return {
        model["id"]: model["go_name"]
        for model in target_models(target, catalog)
        if model.get("id")
    }


def pricing_entries(
    target: Target, catalog: Mapping[str, Any], table: Table
) -> list[Mapping[str, Any]]:
    entries = list((catalog.get("pricing") or {}).get(table.json_name, []))
    if not target.adapter:
        return entries
    allowed = {
        model["id"]
        for model in target_models(target, catalog)
        if model.get("id")
    }
    return [entry for entry in entries if entry["model"] in allowed]


def render_pricing(target: Target, catalog: Mapping[str, Any]) -> str:
    needs_llm = any(table.go_type.startswith("llm.") for table in target.tables)
    lines = [GENERATED_HEADER, "", f"package {target.package}"]
    if needs_llm:
        lines.extend(("", 'import "github.com/deepnoodle-ai/dive/llm"'))
    constants = model_constant_by_id(target, catalog)
    for table in target.tables:
        entries = pricing_entries(target, catalog, table)
        lines.extend(
            (
                "",
                f"// {table.go_name} is generated from catalog.json.",
                f"var {table.go_name} = map[string]{table.go_type}{{",
            )
        )
        for entry in entries:
            note = entry.get("note")
            if note:
                lines.extend(f"\t{line}" for line in comment_lines(note))
            model_id = entry["model"]
            key = constants.get(model_id, go_string(model_id))
            lines.append(f"\t{key}: {{")
            lines.append(f"\t\tModel: {key},")
            if table.kind == "text":
                fields = (
                    ("InputPrice", "input_price_per_1m_tokens"),
                    ("OutputPrice", "output_price_per_1m_tokens"),
                    (
                        "LongContextInputPrice",
                        "long_context_input_price_per_1m_tokens",
                    ),
                    (
                        "LongContextCacheReadPrice",
                        "long_context_cache_read_price_per_1m_tokens",
                    ),
                    (
                        "LongContextOutputPrice",
                        "long_context_output_price_per_1m_tokens",
                    ),
                    ("CacheReadPrice", "cache_read_price_per_1m_tokens"),
                    (
                        "CacheReadPriceAboveThreshold",
                        "cache_read_price_above_threshold_per_1m_tokens",
                    ),
                    ("CacheWritePrice", "cache_write_price_per_1m_tokens"),
                    ("NonGlobalPriceMultiplier", "non_global_price_multiplier"),
                )
            elif table.kind == "image":
                fields = (("Price", "price_per_image"),)
            else:
                fields = (("Price", "price_per_1m_tokens"),)
            for go_field, json_field in fields:
                value = entry.get(json_field)
                if value not in (None, ""):
                    lines.append(f"\t\t{go_field}: {value},")
            if table.kind == "text":
                for go_field, json_field in (
                    (
                        "InputPriceByModality",
                        "input_price_per_1m_tokens_by_modality",
                    ),
                    (
                        "OutputPriceByModality",
                        "output_price_per_1m_tokens_by_modality",
                    ),
                    (
                        "CacheReadPriceByModality",
                        "cache_read_price_per_1m_tokens_by_modality",
                    ),
                ):
                    prices = entry.get(json_field)
                    if prices:
                        rendered = ", ".join(
                            f"{go_string(modality)}: {prices[modality]}"
                            for modality in sorted(prices)
                        )
                        lines.append(
                            f"\t\t{go_field}: map[string]float64{{{rendered}}},"
                        )
            if table.kind == "text" and entry.get("cache_read_price_threshold_tokens"):
                lines.append(
                    "\t\tCacheReadPriceThreshold: "
                    f"{entry['cache_read_price_threshold_tokens']},"
                )
            if table.kind == "text" and entry.get("long_context_threshold_tokens"):
                lines.append(
                    "\t\tLongContextThreshold: "
                    f"{entry['long_context_threshold_tokens']},"
                )
            if table.kind == "image" and entry.get("max_size"):
                lines.append(f"\t\tMaxSize: {go_string(entry['max_size'])},")
            lines.extend(
                (
                    f"\t\tCurrency: {go_string(entry['currency'])},",
                    f"\t\tUpdatedAt: {go_string(entry['updated_at'])},",
                    "\t},",
                )
            )
        lines.append("}")
    lines.append("")
    return "\n".join(lines)


def generated_files(target: Target, catalog: Mapping[str, Any]) -> dict[Path, str | None]:
    files: dict[Path, str | None] = {
        target.directory / "models_gen.go": render_models(target, catalog),
        target.directory / "pricing_gen.go": render_pricing(target, catalog),
    }
    if target.embed:
        files[target.directory / "catalog_gen.go"] = render_catalog_embed(target)
        # None means "must not exist": dropping the last feature flag deletes
        # the generated file instead of orphaning stale constants.
        files[target.directory / "features_gen.go"] = render_features(target, catalog)
    return files


def gofmt(content: str) -> str:
    if GOFMT is None:
        raise CatalogError("gofmt not found on PATH")
    process = subprocess.run(
        [GOFMT],
        input=content,
        text=True,
        capture_output=True,
        check=False,
    )
    if process.returncode != 0:
        raise CatalogError(f"gofmt failed: {process.stderr.strip()}")
    return process.stdout


def selected_targets(names: Sequence[str] | None) -> Iterable[Target]:
    for name in names or TARGETS:
        yield TARGETS[name]


def run(targets: Iterable[Target], check: bool) -> int:
    failed = False
    catalogs: dict[str, dict[str, Any]] = {}
    for target in targets:
        catalog = catalogs.setdefault(
            target.source_provider, read_catalog(target.source_provider)
        )
        for path, content in generated_files(target, catalog).items():
            if content is None:
                if not path.exists():
                    continue
                if check:
                    print(
                        f"stale, no longer generated: {path.relative_to(REPO_ROOT)}",
                        file=sys.stderr,
                    )
                    failed = True
                else:
                    path.unlink()
                    print(f"removed {path.relative_to(REPO_ROOT)}")
                continue
            rendered = gofmt(content)
            if check:
                try:
                    current = path.read_text(encoding="utf-8")
                except OSError:
                    current = ""
                if current != rendered:
                    print(f"out of date: {path.relative_to(REPO_ROOT)}", file=sys.stderr)
                    failed = True
            else:
                path.write_text(rendered, encoding="utf-8")
                print(f"wrote {path.relative_to(REPO_ROOT)}")
    return 1 if failed else 0


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--provider",
        dest="providers",
        action="append",
        choices=tuple(TARGETS),
        help="generation target; repeat to select multiple (default: all)",
    )
    parser.add_argument(
        "--check", action="store_true", help="fail if generated files are stale"
    )
    return parser


def main(argv: Sequence[str] | None = None) -> int:
    args = build_parser().parse_args(argv)
    try:
        return run(selected_targets(args.providers), args.check)
    except (CatalogError, OSError) as error:
        print(error, file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
