// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package meta

const (
	ModelMuseSpark13            = "muse-spark-1.3"
	ModelMuseSpark13Contributor = "muse-spark-1.3-contributor"
	ModelMuseSpark12            = "muse-spark-1.2"
	ModelMuseSpark12Contributor = "muse-spark-1.2-contributor"
	ModelMuseSpark11            = "muse-spark-1.1"
)

// DefaultModel is generated from the catalog's default model.
var DefaultModel = ModelMuseSpark13
