// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package meta

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{
	// Standard tier. Meta publishes no long-context premium: one rate at any context length.
	ModelMuseSpark13: {
		Model:          ModelMuseSpark13,
		InputPrice:     1.25,
		OutputPrice:    4.25,
		CacheReadPrice: 0.15,
		Currency:       "USD",
		UpdatedAt:      "2026-09-02",
	},
	// Contributor tier: discounted in exchange for permission to train on your prompts and completions.
	ModelMuseSpark13Contributor: {
		Model:          ModelMuseSpark13Contributor,
		InputPrice:     0.10,
		OutputPrice:    0.20,
		CacheReadPrice: 0.002,
		Currency:       "USD",
		UpdatedAt:      "2026-09-02",
	},
	ModelMuseSpark12: {
		Model:          ModelMuseSpark12,
		InputPrice:     1.25,
		OutputPrice:    4.25,
		CacheReadPrice: 0.15,
		Currency:       "USD",
		UpdatedAt:      "2026-09-02",
	},
	// Contributor tier: discounted in exchange for permission to train on your prompts and completions.
	ModelMuseSpark12Contributor: {
		Model:          ModelMuseSpark12Contributor,
		InputPrice:     0.10,
		OutputPrice:    0.20,
		CacheReadPrice: 0.002,
		Currency:       "USD",
		UpdatedAt:      "2026-09-02",
	},
	ModelMuseSpark11: {
		Model:          ModelMuseSpark11,
		InputPrice:     1.25,
		OutputPrice:    4.25,
		CacheReadPrice: 0.15,
		Currency:       "USD",
		UpdatedAt:      "2026-09-02",
	},
}
