// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package openrouter

const (
	ModelClaudeFable5       = "anthropic/claude-fable-5"
	ModelClaudeSonnet5      = "anthropic/claude-sonnet-5"
	ModelClaudeOpus48       = "anthropic/claude-opus-4-8"
	ModelClaudeOpus47       = "anthropic/claude-opus-4-7"
	ModelClaudeOpus46       = "anthropic/claude-opus-4-6"
	ModelClaudeSonnet46     = "anthropic/claude-sonnet-4-6"
	ModelClaudeOpus45       = "anthropic/claude-opus-4-5"
	ModelClaudeSonnet45     = "anthropic/claude-sonnet-4-5"
	ModelClaudeHaiku45      = "anthropic/claude-haiku-4-5"
	ModelClaudeOpus41       = "anthropic/claude-opus-4-1"
	ModelClaudeSonnet4      = "anthropic/claude-sonnet-4"
	ModelGPT55              = "openai/gpt-5.5"
	ModelGPT54              = "openai/gpt-5.4"
	ModelGPT54Mini          = "openai/gpt-5.4-mini"
	ModelGPT54Nano          = "openai/gpt-5.4-nano"
	ModelGPT52              = "openai/gpt-5.2"
	ModelGPT51              = "openai/gpt-5.1"
	ModelGPT5               = "openai/gpt-5"
	ModelGPT5Mini           = "openai/gpt-5-mini"
	ModelGPT5Nano           = "openai/gpt-5-nano"
	ModelGPT4o              = "openai/gpt-4o"
	ModelO3                 = "openai/o3"
	ModelO3Pro              = "openai/o3-pro"
	ModelO4Mini             = "openai/o4-mini"
	ModelGemini31ProPreview = "google/gemini-3.1-pro-preview"
	// Deprecated: Model was shut down March 9, 2026.
	ModelGemini3ProPreview   = "google/gemini-3-pro-preview"
	ModelGemini3FlashPreview = "google/gemini-3-flash-preview"
	ModelGemini25Pro         = "google/gemini-2.5-pro"
	ModelGemini25Flash       = "google/gemini-2.5-flash"
	ModelGrok41FastReasoning = "x-ai/grok-4-1-fast-reasoning"
	ModelGrok4FastReasoning  = "x-ai/grok-4-fast-reasoning"
	ModelGrok3               = "x-ai/grok-3"
	ModelMistralLarge3       = "mistral/mistral-large-3"
	ModelDeepSeekR1          = "deepseek/deepseek-r1-0528"
)

// DefaultModel is generated from the catalog's default model.
var DefaultModel = ModelClaudeOpus48
