// Code generated by scripts/generate_provider_catalogs.py; DO NOT EDIT.

package openrouter

import "github.com/deepnoodle-ai/dive/llm"

// TextModelPricing is generated from catalog.json.
var TextModelPricing = map[string]llm.PricingInfo{
	// OpenRouter public model listing, standard route.
	ModelClaudeSonnet55: {
		Model:           ModelClaudeSonnet55,
		InputPrice:      2,
		OutputPrice:     10,
		CacheReadPrice:  0.2,
		CacheWritePrice: 2.5,
		Currency:        "USD",
		UpdatedAt:       "2026-09-30",
	},
	// OpenRouter public model listing, standard route.
	ModelGPT61Sol: {
		Model:                      ModelGPT61Sol,
		InputPrice:                 2,
		OutputPrice:                10,
		LongContextInputPrice:      4,
		LongContextCacheReadPrice:  0.2,
		LongContextOutputPrice:     15,
		CacheReadPrice:             0.1,
		CacheWritePrice:            2.5,
		LongContextCacheWritePrice: 5,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-30",
	},
	// OpenRouter public model listing, standard route. Pro routes spend more reasoning tokens at the same token rates.
	ModelGPT61SolPro: {
		Model:                      ModelGPT61SolPro,
		InputPrice:                 2,
		OutputPrice:                10,
		LongContextInputPrice:      4,
		LongContextCacheReadPrice:  0.2,
		LongContextOutputPrice:     15,
		CacheReadPrice:             0.1,
		CacheWritePrice:            2.5,
		LongContextCacheWritePrice: 5,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-30",
	},
	// OpenRouter public model listing, standard route.
	ModelGPT6Astra: {
		Model:                      ModelGPT6Astra,
		InputPrice:                 10,
		OutputPrice:                50,
		LongContextInputPrice:      20,
		LongContextCacheReadPrice:  2,
		LongContextOutputPrice:     75,
		CacheReadPrice:             1,
		CacheWritePrice:            12.5,
		LongContextCacheWritePrice: 25,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-30",
	},
	// OpenRouter public model listing, standard route. Pro routes spend more reasoning tokens at the same token rates.
	ModelGPT6AstraPro: {
		Model:                      ModelGPT6AstraPro,
		InputPrice:                 10,
		OutputPrice:                50,
		LongContextInputPrice:      20,
		LongContextCacheReadPrice:  2,
		LongContextOutputPrice:     75,
		CacheReadPrice:             1,
		CacheWritePrice:            12.5,
		LongContextCacheWritePrice: 25,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-30",
	},
	// OpenRouter public model listing, standard route. Pro routes spend more reasoning tokens at the same token rates.
	ModelGPT6SolPro: {
		Model:                      ModelGPT6SolPro,
		InputPrice:                 2,
		OutputPrice:                10,
		LongContextInputPrice:      4,
		LongContextCacheReadPrice:  0.4,
		LongContextOutputPrice:     15,
		CacheReadPrice:             0.2,
		CacheWritePrice:            2.5,
		LongContextCacheWritePrice: 5,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-30",
	},
	// OpenRouter public model listing, standard route. Pro routes spend more reasoning tokens at the same token rates.
	ModelGPT6LunaPro: {
		Model:                      ModelGPT6LunaPro,
		InputPrice:                 0.1,
		OutputPrice:                0.5,
		LongContextInputPrice:      0.2,
		LongContextCacheReadPrice:  0.02,
		LongContextOutputPrice:     0.75,
		CacheReadPrice:             0.01,
		CacheWritePrice:            0.125,
		LongContextCacheWritePrice: 0.25,
		LongContextThreshold:       272001,
		Currency:                   "USD",
		UpdatedAt:                  "2026-09-30",
	},
	ModelClaudeSonnet4: {
		Model:          ModelClaudeSonnet4,
		InputPrice:     3.00,
		OutputPrice:    15.00,
		CacheReadPrice: 0.3,
		Currency:       "USD",
		UpdatedAt:      "2026-09-30",
	},
	ModelClaudeOpus41: {
		Model:          ModelClaudeOpus41,
		InputPrice:     15.00,
		OutputPrice:    75.00,
		CacheReadPrice: 1.5,
		Currency:       "USD",
		UpdatedAt:      "2026-09-30",
	},
	ModelGPT5: {
		Model:          ModelGPT5,
		InputPrice:     1.25,
		OutputPrice:    10,
		CacheReadPrice: 0.125,
		Currency:       "USD",
		UpdatedAt:      "2026-09-30",
	},
	ModelGPT4o: {
		Model:          ModelGPT4o,
		InputPrice:     2.50,
		OutputPrice:    10.00,
		CacheReadPrice: 1.25,
		Currency:       "USD",
		UpdatedAt:      "2026-09-30",
	},
	ModelGemini25Flash: {
		Model:          ModelGemini25Flash,
		InputPrice:     0.30,
		OutputPrice:    2.50,
		CacheReadPrice: 0.03,
		Currency:       "USD",
		UpdatedAt:      "2026-09-30",
	},
	ModelGemini25Pro: {
		Model:          ModelGemini25Pro,
		InputPrice:     1.25,
		OutputPrice:    10.00,
		CacheReadPrice: 0.125,
		Currency:       "USD",
		UpdatedAt:      "2026-09-30",
	},
	// OpenRouter public model listing. Routing and provider-specific pricing can change the billed cost.
	ModelDeepSeekV41Flash: {
		Model:          ModelDeepSeekV41Flash,
		InputPrice:     0.0198,
		OutputPrice:    0.396,
		CacheReadPrice: 0.00291,
		Currency:       "USD",
		UpdatedAt:      "2026-09-30",
	},
	ModelDeepSeekR1: {
		Model:          ModelDeepSeekR1,
		InputPrice:     0.50,
		OutputPrice:    2.15,
		CacheReadPrice: 0.35,
		Currency:       "USD",
		UpdatedAt:      "2026-09-30",
	},
}

// ImageModelPricing is generated from catalog.json.
var ImageModelPricing = map[string]llm.ImagePricingInfo{
	"openai/dall-e-3": {
		Model:     "openai/dall-e-3",
		Price:     0.040,
		MaxSize:   "1024x1024",
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
	"stability-ai/stable-diffusion-xl": {
		Model:     "stability-ai/stable-diffusion-xl",
		Price:     0.035,
		MaxSize:   "1024x1024",
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
}

// EmbeddingModelPricing is generated from catalog.json.
var EmbeddingModelPricing = map[string]llm.EmbeddingPricingInfo{
	"openai/text-embedding-3-small": {
		Model:     "openai/text-embedding-3-small",
		Price:     0.020,
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
	"openai/text-embedding-3-large": {
		Model:     "openai/text-embedding-3-large",
		Price:     0.130,
		Currency:  "USD",
		UpdatedAt: "2025-01-15",
	},
}
